package require -exact qsys 15.0
set_module_property NAME atax_internal
set_module_property VERSION 1.0
set_module_property INTERNAL true
set_module_property GROUP HLS
set_module_property DISPLAY_NAME atax_internal
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property SUPPORTED_DEVICE_FAMILIES {"Cyclone 10 GX"}
set_module_assignment hls.cosim.name {_Z4ataxPA64_fPfS1_}
set_module_assignment hls.compressed.name {atax}

#### Synthesis fileset
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL atax_internal
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file "dspba_library_ver.sv" SYSTEM_VERILOG PATH "linux64/lib/dspba/Libraries/sv/base/dspba_library_ver.sv"
add_fileset_file "acl_data_fifo.v" SYSTEM_VERILOG PATH "ip/acl_data_fifo.v"
add_fileset_file "acl_fifo.v" SYSTEM_VERILOG PATH "ip/acl_fifo.v"
add_fileset_file "acl_altera_syncram_wrapped.sv" SYSTEM_VERILOG PATH "ip/acl_altera_syncram_wrapped.sv"
add_fileset_file "acl_scfifo_wrapped.sv" SYSTEM_VERILOG PATH "ip/acl_scfifo_wrapped.sv"
add_fileset_file "acl_ecc_decoder.sv" SYSTEM_VERILOG PATH "ip/acl_ecc_decoder.sv"
add_fileset_file "acl_ecc_encoder.sv" SYSTEM_VERILOG PATH "ip/acl_ecc_encoder.sv"
add_fileset_file "acl_ecc.svh" SYSTEM_VERILOG PATH "ip/acl_ecc.svh"
add_fileset_file "acl_ll_fifo.v" SYSTEM_VERILOG PATH "ip/acl_ll_fifo.v"
add_fileset_file "acl_ll_ram_fifo.v" SYSTEM_VERILOG PATH "ip/acl_ll_ram_fifo.v"
add_fileset_file "acl_valid_fifo_counter.v" SYSTEM_VERILOG PATH "ip/acl_valid_fifo_counter.v"
add_fileset_file "acl_dspba_valid_fifo_counter.v" SYSTEM_VERILOG PATH "ip/acl_dspba_valid_fifo_counter.v"
add_fileset_file "acl_staging_reg.v" SYSTEM_VERILOG PATH "ip/acl_staging_reg.v"
add_fileset_file "hld_fifo.sv" SYSTEM_VERILOG PATH "ip/hld_fifo.sv"
add_fileset_file "acl_mid_speed_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_mid_speed_fifo.sv"
add_fileset_file "acl_latency_one_ram_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_latency_one_ram_fifo.sv"
add_fileset_file "acl_latency_zero_ram_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_latency_zero_ram_fifo.sv"
add_fileset_file "hld_fifo_zero_width.sv" SYSTEM_VERILOG PATH "ip/hld_fifo_zero_width.sv"
add_fileset_file "acl_high_speed_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_high_speed_fifo.sv"
add_fileset_file "acl_low_latency_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_low_latency_fifo.sv"
add_fileset_file "acl_zero_latency_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_zero_latency_fifo.sv"
add_fileset_file "acl_fanout_pipeline.sv" SYSTEM_VERILOG PATH "ip/acl_fanout_pipeline.sv"
add_fileset_file "acl_std_synchronizer_nocut.v" SYSTEM_VERILOG PATH "ip/acl_std_synchronizer_nocut.v"
add_fileset_file "acl_tessellated_incr_decr_threshold.sv" SYSTEM_VERILOG PATH "ip/acl_tessellated_incr_decr_threshold.sv"
add_fileset_file "acl_tessellated_incr_lookahead.sv" SYSTEM_VERILOG PATH "ip/acl_tessellated_incr_lookahead.sv"
add_fileset_file "acl_reset_handler.sv" SYSTEM_VERILOG PATH "ip/acl_reset_handler.sv"
add_fileset_file "acl_lfsr.sv" SYSTEM_VERILOG PATH "ip/acl_lfsr.sv"
add_fileset_file "acl_mlab_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_mlab_fifo.sv"
add_fileset_file "acl_parameter_assert.svh" SYSTEM_VERILOG PATH "ip/acl_parameter_assert.svh"
add_fileset_file "acl_pop.v" SYSTEM_VERILOG PATH "ip/acl_pop.v"
add_fileset_file "acl_push.v" SYSTEM_VERILOG PATH "ip/acl_push.v"
add_fileset_file "acl_token_fifo_counter.v" SYSTEM_VERILOG PATH "ip/acl_token_fifo_counter.v"
add_fileset_file "acl_pipeline.v" SYSTEM_VERILOG PATH "ip/acl_pipeline.v"
add_fileset_file "acl_dspba_buffer.v" SYSTEM_VERILOG PATH "ip/acl_dspba_buffer.v"
add_fileset_file "acl_enable_sink.v" SYSTEM_VERILOG PATH "ip/acl_enable_sink.v"
add_fileset_file "hld_iord.sv" SYSTEM_VERILOG PATH "ip/hld_iord.sv"
add_fileset_file "hld_iord_stall_latency.sv" SYSTEM_VERILOG PATH "ip/hld_iord_stall_latency.sv"
add_fileset_file "hld_iord_stall_valid.sv" SYSTEM_VERILOG PATH "ip/hld_iord_stall_valid.sv"
add_fileset_file "hld_memory_depth_quantization.svh" SYSTEM_VERILOG PATH "ip/hld_memory_depth_quantization.svh"
add_fileset_file "acl_shift_register_no_reset.sv" SYSTEM_VERILOG PATH "ip/acl_shift_register_no_reset.sv"
add_fileset_file "acl_ffwdsrc.v" SYSTEM_VERILOG PATH "ip/acl_ffwdsrc.v"
add_fileset_file "acl_ffwddst.sv" SYSTEM_VERILOG PATH "ip/acl_ffwddst.sv"
add_fileset_file "lsu_top.v" SYSTEM_VERILOG PATH "ip/lsu_top.v"
add_fileset_file "lsu_permute_address.v" SYSTEM_VERILOG PATH "ip/lsu_permute_address.v"
add_fileset_file "lsu_pipelined.v" SYSTEM_VERILOG PATH "ip/lsu_pipelined.v"
add_fileset_file "lsu_enabled.v" SYSTEM_VERILOG PATH "ip/lsu_enabled.v"
add_fileset_file "lsu_basic_coalescer.v" SYSTEM_VERILOG PATH "ip/lsu_basic_coalescer.v"
add_fileset_file "lsu_simple.v" SYSTEM_VERILOG PATH "ip/lsu_simple.v"
add_fileset_file "lsu_streaming.v" SYSTEM_VERILOG PATH "ip/lsu_streaming.v"
add_fileset_file "lsu_burst_master.v" SYSTEM_VERILOG PATH "ip/lsu_burst_master.v"
add_fileset_file "lsu_bursting_load_stores.v" SYSTEM_VERILOG PATH "ip/lsu_bursting_load_stores.v"
add_fileset_file "lsu_non_aligned_write.v" SYSTEM_VERILOG PATH "ip/lsu_non_aligned_write.v"
add_fileset_file "lsu_read_cache.v" SYSTEM_VERILOG PATH "ip/lsu_read_cache.v"
add_fileset_file "lsu_atomic.v" SYSTEM_VERILOG PATH "ip/lsu_atomic.v"
add_fileset_file "lsu_prefetch_block.v" SYSTEM_VERILOG PATH "ip/lsu_prefetch_block.v"
add_fileset_file "lsu_wide_wrapper.v" SYSTEM_VERILOG PATH "ip/lsu_wide_wrapper.v"
add_fileset_file "lsu_streaming_prefetch.v" SYSTEM_VERILOG PATH "ip/lsu_streaming_prefetch.v"
add_fileset_file "acl_aligned_burst_coalesced_lsu.v" SYSTEM_VERILOG PATH "ip/acl_aligned_burst_coalesced_lsu.v"
add_fileset_file "acl_toggle_detect.v" SYSTEM_VERILOG PATH "ip/acl_toggle_detect.v"
add_fileset_file "acl_debug_mem.v" SYSTEM_VERILOG PATH "ip/acl_debug_mem.v"
add_fileset_file "lsu_burst_coalesced_pipelined_write.sv" SYSTEM_VERILOG PATH "ip/lsu_burst_coalesced_pipelined_write.sv"
add_fileset_file "lsu_burst_coalesced_pipelined_read.sv" SYSTEM_VERILOG PATH "ip/lsu_burst_coalesced_pipelined_read.sv"
add_fileset_file "acl_fifo_stall_valid_lookahead.sv" SYSTEM_VERILOG PATH "ip/acl_fifo_stall_valid_lookahead.sv"
add_fileset_file "hld_global_load_store.sv" SYSTEM_VERILOG PATH "ip/hld_global_load_store.sv"
add_fileset_file "hld_lsu.sv" SYSTEM_VERILOG PATH "ip/hld_lsu.sv"
add_fileset_file "hld_lsu_burst_coalescer.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_burst_coalescer.sv"
add_fileset_file "hld_lsu_coalescer_dynamic_timeout.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_coalescer_dynamic_timeout.sv"
add_fileset_file "hld_lsu_data_aligner.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_data_aligner.sv"
add_fileset_file "hld_lsu_read_cache.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_read_cache.sv"
add_fileset_file "hld_lsu_read_data_alignment.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_read_data_alignment.sv"
add_fileset_file "hld_lsu_unaligned_controller.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_unaligned_controller.sv"
add_fileset_file "hld_lsu_word_coalescer.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_word_coalescer.sv"
add_fileset_file "hld_lsu_write_data_alignment.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_write_data_alignment.sv"
add_fileset_file "hld_lsu_write_kernel_downstream.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_write_kernel_downstream.sv"
add_fileset_file "acl_full_detector.v" SYSTEM_VERILOG PATH "ip/acl_full_detector.v"
add_fileset_file "acl_tessellated_incr_decr_decr.sv" SYSTEM_VERILOG PATH "ip/acl_tessellated_incr_decr_decr.sv"
add_fileset_file "hld_iowr.sv" SYSTEM_VERILOG PATH "ip/hld_iowr.sv"
add_fileset_file "hld_iowr_stall_latency.sv" SYSTEM_VERILOG PATH "ip/hld_iowr_stall_latency.sv"
add_fileset_file "hld_iowr_stall_valid.sv" SYSTEM_VERILOG PATH "ip/hld_iowr_stall_valid.sv"
add_fileset_file "acl_loop_limiter.v" SYSTEM_VERILOG PATH "ip/acl_loop_limiter.v"
add_fileset_file "hld_loop_profiler.sv" SYSTEM_VERILOG PATH "ip/hld_loop_profiler.sv"
add_fileset_file "hld_sim_latency_tracker.sv" SYSTEM_VERILOG PATH "ip/hld_sim_latency_tracker.sv"
add_fileset_file "acl_reset_wire.v" SYSTEM_VERILOG PATH "ip/acl_reset_wire.v"
add_fileset_file "atax_function_wrapper.sv" SYSTEM_VERILOG PATH "ip/atax_function_wrapper.sv"
add_fileset_file "atax_function.sv" SYSTEM_VERILOG PATH "ip/atax_function.sv"
add_fileset_file "atax_bb_B0_runOnce.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B0_runOnce.sv"
add_fileset_file "atax_B0_runOnce_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B0_runOnce_branch.sv"
add_fileset_file "atax_B0_runOnce_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B0_runOnce_merge.sv"
add_fileset_file "atax_bb_B0_runOnce_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B0_runOnce_stall_region.sv"
add_fileset_file "atax_B0_runOnce_merge_reg.sv" SYSTEM_VERILOG PATH "ip/atax_B0_runOnce_merge_reg.sv"
add_fileset_file "atax_i_llvm_fpga_pop_token_i1_wt_limpop_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_token_i1_wt_limpop_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_token_i1_wt_limpop_0_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_token_i1_wt_limpop_0_reg.sv"
add_fileset_file "atax_i_llvm_fpga_push_token_i1_wt_limpush_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_token_i1_wt_limpush_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_token_i1_wt_limpush_1_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_token_i1_wt_limpush_1_reg.sv"
add_fileset_file "atax_bb_B10.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B10.sv"
add_fileset_file "atax_B10_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B10_branch.sv"
add_fileset_file "atax_B10_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B10_merge.sv"
add_fileset_file "atax_bb_B10_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B10_stall_region.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_memdep_phi_push20_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_memdep_phi_push20_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_memdep_phi_push20_0_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_memdep_phi_push20_0_reg.sv"
add_fileset_file "atax_bb_B11.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B11.sv"
add_fileset_file "atax_B11_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B11_branch.sv"
add_fileset_file "atax_B11_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B11_merge.sv"
add_fileset_file "atax_bb_B11_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B11_stall_region.sv"
add_fileset_file "atax_bb_B13.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B13.sv"
add_fileset_file "atax_B13_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B13_branch.sv"
add_fileset_file "atax_B13_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B13_merge.sv"
add_fileset_file "atax_bb_B13_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B13_stall_region.sv"
add_fileset_file "atax_i_iowr_bl_return_unnamed_atax21_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_iowr_bl_return_unnamed_atax21_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_push_token_i1_throttle_push_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_token_i1_throttle_push_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_token_i1_throttle_push_1_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_token_i1_throttle_push_1_reg.sv"
add_fileset_file "atax_bb_B2.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B2.sv"
add_fileset_file "atax_B2_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B2_branch.sv"
add_fileset_file "atax_B2_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B2_merge.sv"
add_fileset_file "atax_bb_B2_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B2_stall_region.sv"
add_fileset_file "atax_bb_B5.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B5.sv"
add_fileset_file "atax_B5_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B5_branch.sv"
add_fileset_file "atax_B5_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B5_merge.sv"
add_fileset_file "atax_bb_B5_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B5_stall_region.sv"
add_fileset_file "atax_bb_B6.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B6.sv"
add_fileset_file "atax_B6_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B6_branch.sv"
add_fileset_file "atax_B6_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B6_merge.sv"
add_fileset_file "atax_bb_B6_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B6_stall_region.sv"
add_fileset_file "atax_B6_merge_reg.sv" SYSTEM_VERILOG PATH "ip/atax_B6_merge_reg.sv"
add_fileset_file "atax_i_sfc_s_c0_in_for_cond24_preheader_s_c0_enter14812_atax1.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c0_in_for_cond24_preheader_s_c0_enter14812_atax1.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_c0000r_s_c0_exit156_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_c0000r_s_c0_exit156_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_c0000_atax1_full_detector.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_c0000_atax1_full_detector.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_c0000t156_atax1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_c0000t156_atax1_data_fifo.sv"
add_fileset_file "atax_i_sfc_logic_s_c0_in_for_cond24_preh0000_c0_enter14812_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c0_in_for_cond24_preh0000_c0_enter14812_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_arrayidx28_promoted14_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_arrayidx28_promoted14_0.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going76_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going76_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i32_i_138_pop19_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i32_i_138_pop19_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i7_fpga_indvars_iv36_pop18_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i7_fpga_indvars_iv36_pop18_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notexitcond77_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notexitcond77_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i32_i_138_push19_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i32_i_138_push19_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i7_fpga_indvars_iv36_push18_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i7_fpga_indvars_iv36_push18_0.sv"
add_fileset_file "atax_bb_B7.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B7.sv"
add_fileset_file "atax_B7_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B7_branch.sv"
add_fileset_file "atax_B7_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B7_merge.sv"
add_fileset_file "atax_bb_B7_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B7_stall_region.sv"
add_fileset_file "atax_B7_merge_reg.sv" SYSTEM_VERILOG PATH "ip/atax_B7_merge_reg.sv"
add_fileset_file "atax_i_sfc_s_c0_in_for_body26_s_c0_enter16615_atax1.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c0_in_for_body26_s_c0_enter16615_atax1.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_body26_s_c0_exit178_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_body26_s_c0_exit178_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000_atax1_full_detector.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000_atax1_full_detector.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000t178_atax1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000t178_atax1_data_fifo.sv"
add_fileset_file "atax_i_sfc_logic_s_c0_in_for_body26_s_c0_enter16615_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c0_in_for_body26_s_c0_enter16615_atax0.sv"
add_fileset_file "atax_flt_i_sfc_logic_s_c0_in_for_body26_0000xk5id06uq0cp0jv34qcz.sv" SYSTEM_VERILOG PATH "ip/atax_flt_i_sfc_logic_s_c0_in_for_body26_0000xk5id06uq0cp0jv34qcz.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_16_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_16_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_17_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_17_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going62_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going62_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_f32_add41_pop34_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_f32_add41_pop34_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i1_exitcond38112_pop40_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i1_exitcond38112_pop40_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i1_forked105108_pop37_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i1_forked105108_pop37_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i1_notcmp74114_pop41_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i1_notcmp74114_pop41_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i2_cleanups65_pop36_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i2_cleanups65_pop36_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i32_j_137_pop35_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i32_j_137_pop35_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i64_idxprom27109_pop38_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i64_idxprom27109_pop38_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i7_fpga_indvars_iv30_pop33_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i7_fpga_indvars_iv30_pop33_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_p67f32_arrayidx2812111_pop39_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_p67f32_arrayidx2812111_pop39_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_f32_add41_push34_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_f32_add41_push34_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_exitcond38112_push40_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_exitcond38112_push40_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_forked105108_push37_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_forked105108_push37_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_lastiniteration64_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_lastiniteration64_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notcmp74114_push41_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notcmp74114_push41_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notexitcond72_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notexitcond72_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i2_cleanups65_push36_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i2_cleanups65_push36_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i32_j_137_push35_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i32_j_137_push35_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i64_idxprom27109_push38_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i64_idxprom27109_push38_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i7_fpga_indvars_iv30_push33_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i7_fpga_indvars_iv30_push33_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_p67f32_arrayidx2812111_push39_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_p67f32_arrayidx2812111_push39_0.sv"
add_fileset_file "atax_bb_B8.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B8.sv"
add_fileset_file "atax_B8_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B8_branch.sv"
add_fileset_file "atax_B8_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B8_merge.sv"
add_fileset_file "atax_bb_B8_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B8_stall_region.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i1_memdep_phi_pop20_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i1_memdep_phi_pop20_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i1_memdep_phi_pop20_0_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i1_memdep_phi_pop20_0_reg.sv"
add_fileset_file "atax_i_sfc_s_c0_in_for_inc40_s_c0_enter189_atax3.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c0_in_for_inc40_s_c0_enter189_atax3.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_inc40_s_c0_exit193_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_inc40_s_c0_exit193_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_i0000_atax1_full_detector.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_i0000_atax1_full_detector.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_i0000t193_atax1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_i0000t193_atax1_data_fifo.sv"
add_fileset_file "atax_i_sfc_logic_s_c0_in_for_inc40_s_c0_enter189_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c0_in_for_inc40_s_c0_enter189_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memdep_17233_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memdep_17233_0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_18_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_18_atax0.sv"
add_fileset_file "atax_bb_B9.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B9.sv"
add_fileset_file "atax_B9_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B9_branch.sv"
add_fileset_file "atax_B9_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B9_merge.sv"
add_fileset_file "atax_bb_B9_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B9_stall_region.sv"
add_fileset_file "atax_B9_merge_reg.sv" SYSTEM_VERILOG PATH "ip/atax_B9_merge_reg.sv"
add_fileset_file "atax_i_sfc_s_c0_in_for_body48_s_c0_enter20116_atax1.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c0_in_for_body48_s_c0_enter20116_atax1.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_body48_s_c0_exit213_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_body48_s_c0_exit213_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0001_atax1_full_detector.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0001_atax1_full_detector.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000t213_atax1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000t213_atax1_data_fifo.sv"
add_fileset_file "atax_i_sfc_logic_s_c0_in_for_body48_s_c0_enter20116_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c0_in_for_body48_s_c0_enter20116_atax0.sv"
add_fileset_file "atax_flt_i_sfc_logic_s_c0_in_for_body48_0000xk5id06uq0cp0jv34qcz.sv" SYSTEM_VERILOG PATH "ip/atax_flt_i_sfc_logic_s_c0_in_for_body48_0000xk5id06uq0cp0jv34qcz.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going46_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going46_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_f32_pop48_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_f32_pop48_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i1_exitcond38113_pop46_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i1_exitcond38113_pop46_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i1_memdep_phi_pop20116_pop49_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i1_memdep_phi_pop20116_pop49_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i1_notcmp74115_pop47_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i1_notcmp74115_pop47_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i2_cleanups49_pop44_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i2_cleanups49_pop44_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i32_j_235_pop43_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i32_j_235_pop43_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i5_fpga_indvars_iv33_pop42_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i5_fpga_indvars_iv33_pop42_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i64_idxprom27110_pop45_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i64_idxprom27110_pop45_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_f32_push48_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_f32_push48_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_exitcond38113_push46_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_exitcond38113_push46_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_lastiniteration48_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_lastiniteration48_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_memdep_phi_pop20116_push49_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_memdep_phi_pop20116_push49_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notcmp74115_push47_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notcmp74115_push47_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notexitcond56_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notexitcond56_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i2_cleanups49_push44_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i2_cleanups49_push44_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i32_j_235_push43_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i32_j_235_push43_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i5_fpga_indvars_iv33_push42_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i5_fpga_indvars_iv33_push42_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i64_idxprom27110_push45_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i64_idxprom27110_push45_0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memcoalesce_load_fpgaunique_1510_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memcoalesce_load_fpgaunique_1510_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memcoalesce_load_fpgaunique_1612_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memcoalesce_load_fpgaunique_1612_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memdep_511_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memdep_511_0.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going101_1_sr.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going101_1_sr.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going101_1_valid_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going101_1_valid_fifo.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going46_6_sr.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going46_6_sr.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going46_6_valid_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going46_6_valid_fifo.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going62_6_sr.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going62_6_sr.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going62_6_valid_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going62_6_valid_fifo.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going76_2_sr.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going76_2_sr.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going76_2_valid_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going76_2_valid_fifo.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going83_6_sr.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going83_6_sr.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going83_6_valid_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going83_6_valid_fifo.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going97_0_sr.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going97_0_sr.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going_2_sr.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going_2_sr.sv"
add_fileset_file "atax_loop_limiter_0.sv" SYSTEM_VERILOG PATH "ip/atax_loop_limiter_0.sv"
add_fileset_file "atax_loop_limiter_1.sv" SYSTEM_VERILOG PATH "ip/atax_loop_limiter_1.sv"
add_fileset_file "atax_loop_limiter_2.sv" SYSTEM_VERILOG PATH "ip/atax_loop_limiter_2.sv"
add_fileset_file "atax_loop_limiter_3.sv" SYSTEM_VERILOG PATH "ip/atax_loop_limiter_3.sv"
add_fileset_file "atax_loop_limiter_4.sv" SYSTEM_VERILOG PATH "ip/atax_loop_limiter_4.sv"
add_fileset_file "atax_loop_limiter_5.sv" SYSTEM_VERILOG PATH "ip/atax_loop_limiter_5.sv"
add_fileset_file "atax_bb_B10_sr_0.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B10_sr_0.sv"
add_fileset_file "atax_bb_B11_sr_0.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B11_sr_0.sv"
add_fileset_file "atax_bb_B12.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B12.sv"
add_fileset_file "atax_B12_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B12_branch.sv"
add_fileset_file "atax_B12_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B12_merge.sv"
add_fileset_file "atax_bb_B12_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B12_stall_region.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memdep_18_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memdep_18_0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memdep_20_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memdep_20_0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memdep_22_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memdep_22_0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memdep_24_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memdep_24_0.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going_0.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going_2_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going_2_reg.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i1_memdep_phi21_pop23_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i1_memdep_phi21_pop23_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i1_memdep_phi21_pop23_5_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i1_memdep_phi21_pop23_5_reg.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i1_memdep_phi23_pop24_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i1_memdep_phi23_pop24_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i1_memdep_phi23_pop24_6_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i1_memdep_phi23_pop24_6_reg.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i1_memdep_phi25_pop25_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i1_memdep_phi25_pop25_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i1_memdep_phi25_pop25_7_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i1_memdep_phi25_pop25_7_reg.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i32_i_334_pop22_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i32_i_334_pop22_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i32_i_334_pop22_4_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i32_i_334_pop22_4_reg.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i4_cleanups_pop27_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i4_cleanups_pop27_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i4_cleanups_pop27_1_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i4_cleanups_pop27_1_reg.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i4_initerations_pop26_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i4_initerations_pop26_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i4_initerations_pop26_3_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i4_initerations_pop26_3_reg.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i5_fpga_indvars_iv39_pop21_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i5_fpga_indvars_iv39_pop21_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i5_fpga_indvars_iv39_pop21_8_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i5_fpga_indvars_iv39_pop21_8_reg.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_lastiniteration_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_lastiniteration_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_lastiniteration_36_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_lastiniteration_36_reg.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_memdep_phi21_push23_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_memdep_phi21_push23_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_memdep_phi21_push23_50_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_memdep_phi21_push23_50_reg.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_memdep_phi23_push24_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_memdep_phi23_push24_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_memdep_phi23_push24_51_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_memdep_phi23_push24_51_reg.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_memdep_phi25_push25_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_memdep_phi25_push25_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_memdep_phi25_push25_52_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_memdep_phi25_push25_52_reg.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notexitcond_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notexitcond_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notexitcond_34_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notexitcond_34_reg.sv"
add_fileset_file "atax_i_llvm_fpga_push_i32_i_334_push22_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i32_i_334_push22_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i32_i_334_push22_31_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i32_i_334_push22_31_reg.sv"
add_fileset_file "atax_i_llvm_fpga_push_i4_cleanups_push27_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i4_cleanups_push27_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i4_cleanups_push27_53_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i4_cleanups_push27_53_reg.sv"
add_fileset_file "atax_i_llvm_fpga_push_i4_initerations_push26_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i4_initerations_push26_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i4_initerations_push26_24_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i4_initerations_push26_24_reg.sv"
add_fileset_file "atax_i_llvm_fpga_push_i5_fpga_indvars_iv39_push21_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i5_fpga_indvars_iv39_push21_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i5_fpga_indvars_iv39_push21_35_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i5_fpga_indvars_iv39_push21_35_reg.sv"
add_fileset_file "atax_B12_merge_reg.sv" SYSTEM_VERILOG PATH "ip/atax_B12_merge_reg.sv"
add_fileset_file "atax_i_llvm_fpga_ffwd_dest_s_struct_z4pa0000unnamed_atax20_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_ffwd_dest_s_struct_z4pa0000unnamed_atax20_atax0.sv"
add_fileset_file "atax_i_sfc_s_c0_in_for_body69_s_c0_enter22113_atax38.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c0_in_for_body69_s_c0_enter22113_atax38.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_body69_s_c0_exit228_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_body69_s_c0_exit228_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0002_atax1_full_detector.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0002_atax1_full_detector.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000t228_atax1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000t228_atax1_data_fifo.sv"
add_fileset_file "atax_i_sfc_logic_s_c0_in_for_body69_s_c0_enter22113_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c0_in_for_body69_s_c0_enter22113_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memcoalesce_load_fpgaunique_1713_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memcoalesce_load_fpgaunique_1713_atax0.sv"
add_fileset_file "atax_bb_B12_sr_1.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B12_sr_1.sv"
add_fileset_file "atax_bb_B13_sr_0.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B13_sr_0.sv"
add_fileset_file "atax_bb_B1_start.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B1_start.sv"
add_fileset_file "atax_B1_start_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B1_start_branch.sv"
add_fileset_file "atax_B1_start_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B1_start_merge.sv"
add_fileset_file "atax_bb_B1_start_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B1_start_stall_region.sv"
add_fileset_file "atax_B1_start_merge_reg.sv" SYSTEM_VERILOG PATH "ip/atax_B1_start_merge_reg.sv"
add_fileset_file "atax_i_llvm_fpga_pop_throttle_i1_throttle_pop_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_throttle_i1_throttle_pop_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_throttle_i1_throttle_pop_1_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_throttle_i1_throttle_pop_1_reg.sv"
add_fileset_file "atax_i_iord_bl_call_unnamed_atax2_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_iord_bl_call_unnamed_atax2_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_ffwd_source_s_struct_z40000_unnamed_atax3_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_ffwd_source_s_struct_z40000_unnamed_atax3_atax0.sv"
add_fileset_file "atax_i_sfc_s_c0_in_wt_entry_s_c0_enter11_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c0_in_wt_entry_s_c0_enter11_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_wt_entry_s_c0_exit_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_wt_entry_s_c0_exit_atax0.sv"
add_fileset_file "atax_i_sfc_logic_s_c0_in_wt_entry_s_c0_enter11_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c0_in_wt_entry_s_c0_enter11_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going101_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going101_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notexitcond102_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notexitcond102_0.sv"
add_fileset_file "atax_bb_B2_sr_0.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B2_sr_0.sv"
add_fileset_file "atax_bb_B3.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B3.sv"
add_fileset_file "atax_B3_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B3_branch.sv"
add_fileset_file "atax_B3_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B3_merge.sv"
add_fileset_file "atax_bb_B3_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B3_stall_region.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memdep_15_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memdep_15_0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memdep_16_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memdep_16_0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memdep_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memdep_0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_5_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_5_atax0.sv"
add_fileset_file "atax_readdata_reg_unnamed_5_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_readdata_reg_unnamed_5_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going97_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going97_0.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going97_0_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going97_0_reg.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i32_i_040_pop17_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i32_i_040_pop17_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i32_i_040_pop17_3_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i32_i_040_pop17_3_reg.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i7_fpga_indvars_iv27_pop16_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i7_fpga_indvars_iv27_pop16_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i7_fpga_indvars_iv27_pop16_13_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i7_fpga_indvars_iv27_pop16_13_reg.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notexitcond98_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notexitcond98_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notexitcond98_17_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notexitcond98_17_reg.sv"
add_fileset_file "atax_i_llvm_fpga_push_i32_i_040_push17_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i32_i_040_push17_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i32_i_040_push17_21_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i32_i_040_push17_21_reg.sv"
add_fileset_file "atax_i_llvm_fpga_push_i7_fpga_indvars_iv27_push16_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i7_fpga_indvars_iv27_push16_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i7_fpga_indvars_iv27_push16_19_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i7_fpga_indvars_iv27_push16_19_reg.sv"
add_fileset_file "atax_B3_merge_reg.sv" SYSTEM_VERILOG PATH "ip/atax_B3_merge_reg.sv"
add_fileset_file "atax_i_llvm_fpga_ffwd_dest_s_struct_z4pa0000_unnamed_atax4_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_ffwd_dest_s_struct_z4pa0000_unnamed_atax4_atax0.sv"
add_fileset_file "atax_bb_B3_sr_1.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B3_sr_1.sv"
add_fileset_file "atax_bb_B4.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B4.sv"
add_fileset_file "atax_B4_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B4_branch.sv"
add_fileset_file "atax_B4_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B4_merge.sv"
add_fileset_file "atax_bb_B4_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B4_stall_region.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_10_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_10_atax0.sv"
add_fileset_file "atax_readdata_reg_unnamed_10_atax4.sv" SYSTEM_VERILOG PATH "ip/atax_readdata_reg_unnamed_10_atax4.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_11_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_11_atax0.sv"
add_fileset_file "atax_readdata_reg_unnamed_11_atax5.sv" SYSTEM_VERILOG PATH "ip/atax_readdata_reg_unnamed_11_atax5.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_12_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_12_atax0.sv"
add_fileset_file "atax_readdata_reg_unnamed_12_atax6.sv" SYSTEM_VERILOG PATH "ip/atax_readdata_reg_unnamed_12_atax6.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_13_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_13_atax0.sv"
add_fileset_file "atax_readdata_reg_unnamed_13_atax7.sv" SYSTEM_VERILOG PATH "ip/atax_readdata_reg_unnamed_13_atax7.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_14_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_14_atax0.sv"
add_fileset_file "atax_readdata_reg_unnamed_14_atax8.sv" SYSTEM_VERILOG PATH "ip/atax_readdata_reg_unnamed_14_atax8.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_7_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_7_atax0.sv"
add_fileset_file "atax_readdata_reg_unnamed_7_atax1.sv" SYSTEM_VERILOG PATH "ip/atax_readdata_reg_unnamed_7_atax1.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_8_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_8_atax0.sv"
add_fileset_file "atax_readdata_reg_unnamed_8_atax2.sv" SYSTEM_VERILOG PATH "ip/atax_readdata_reg_unnamed_8_atax2.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_9_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_9_atax0.sv"
add_fileset_file "atax_readdata_reg_unnamed_9_atax3.sv" SYSTEM_VERILOG PATH "ip/atax_readdata_reg_unnamed_9_atax3.sv"
add_fileset_file "atax_B4_merge_reg.sv" SYSTEM_VERILOG PATH "ip/atax_B4_merge_reg.sv"
add_fileset_file "atax_i_sfc_s_c0_in_for_body9_s_c0_enter14314_atax1.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c0_in_for_body9_s_c0_enter14314_atax1.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_body9_s_c0_exit145_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_body9_s_c0_exit145_atax0.sv"
add_fileset_file "atax_i_sfc_logic_s_c0_in_for_body9_s_c0_enter14314_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c0_in_for_body9_s_c0_enter14314_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going83_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going83_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i1_notcmp95107_pop32_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i1_notcmp95107_pop32_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i2_cleanups86_pop30_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i2_cleanups86_pop30_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i32_j_039_pop29_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i32_j_039_pop29_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i4_fpga_indvars_iv_pop28_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i4_fpga_indvars_iv_pop28_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i64_idxprom106_pop31_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i64_idxprom106_pop31_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_lastiniteration85_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_lastiniteration85_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notcmp95107_push32_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notcmp95107_push32_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notexitcond93_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notexitcond93_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i2_cleanups86_push30_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i2_cleanups86_push30_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i32_j_039_push29_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i32_j_039_push29_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i4_fpga_indvars_iv_push28_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i4_fpga_indvars_iv_push28_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i64_idxprom106_push31_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i64_idxprom106_push31_0.sv"
add_fileset_file "atax_i_llvm_fpga_ffwd_dest_s_struct_z4pa0000_unnamed_atax6_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_ffwd_dest_s_struct_z4pa0000_unnamed_atax6_atax0.sv"
add_fileset_file "atax_i_sfc_s_c1_in_for_body9_s_c1_enter_atax12.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c1_in_for_body9_s_c1_enter_atax12.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c1_out_for_body9_s_c1_exit_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c1_out_for_body9_s_c1_exit_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c1_out_for_b0000_atax1_full_detector.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c1_out_for_b0000_atax1_full_detector.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c1_out_for_b0000exit_atax1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c1_out_for_b0000exit_atax1_data_fifo.sv"
add_fileset_file "atax_i_sfc_logic_s_c1_in_for_body9_s_c1_enter_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c1_in_for_body9_s_c1_enter_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memdep_19_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memdep_19_0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memdep_8_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memdep_8_0.sv"
add_fileset_file "atax_bb_B4_sr_1.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B4_sr_1.sv"
add_fileset_file "atax_bb_B5_sr_0.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B5_sr_0.sv"
add_fileset_file "atax_bb_B6_sr_1.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B6_sr_1.sv"
add_fileset_file "atax_bb_B7_sr_1.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B7_sr_1.sv"
add_fileset_file "atax_bb_B8_sr_0.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B8_sr_0.sv"
add_fileset_file "atax_bb_B9_sr_1.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B9_sr_1.sv"
add_fileset_file "acl_avm_to_ic.v" SYSTEM_VERILOG PATH "ip/acl_avm_to_ic.v"
add_fileset_file "acl_ic_master_endpoint.v" SYSTEM_VERILOG PATH "ip/acl_ic_master_endpoint.v"
add_fileset_file "acl_arb_intf.v" SYSTEM_VERILOG PATH "ip/acl_arb_intf.v"
add_fileset_file "acl_ic_intf.v" SYSTEM_VERILOG PATH "ip/acl_ic_intf.v"
add_fileset_file "acl_ic_slave_endpoint.v" SYSTEM_VERILOG PATH "ip/acl_ic_slave_endpoint.v"
add_fileset_file "acl_ic_slave_rrp.v" SYSTEM_VERILOG PATH "ip/acl_ic_slave_rrp.v"
add_fileset_file "acl_ic_slave_wrp.v" SYSTEM_VERILOG PATH "ip/acl_ic_slave_wrp.v"
add_fileset_file "acl_arb2.v" SYSTEM_VERILOG PATH "ip/acl_arb2.v"
add_fileset_file "acl_ic_to_avm.v" SYSTEM_VERILOG PATH "ip/acl_ic_to_avm.v"
add_fileset_file "acl_mem1x.v" SYSTEM_VERILOG PATH "ip/acl_mem1x.v"
add_fileset_file "hld_ram.sv" SYSTEM_VERILOG PATH "ip/hld_ram.sv"
add_fileset_file "hld_ram_ecc.sv" SYSTEM_VERILOG PATH "ip/hld_ram_ecc.sv"
add_fileset_file "hld_ram_tall_depth_stitch.sv" SYSTEM_VERILOG PATH "ip/hld_ram_tall_depth_stitch.sv"
add_fileset_file "hld_ram_remaining_width.sv" SYSTEM_VERILOG PATH "ip/hld_ram_remaining_width.sv"
add_fileset_file "hld_ram_bits_per_enable.sv" SYSTEM_VERILOG PATH "ip/hld_ram_bits_per_enable.sv"
add_fileset_file "hld_ram_generic_two_way_depth_stitch.sv" SYSTEM_VERILOG PATH "ip/hld_ram_generic_two_way_depth_stitch.sv"
add_fileset_file "hld_ram_generic_three_way_depth_stitch.sv" SYSTEM_VERILOG PATH "ip/hld_ram_generic_three_way_depth_stitch.sv"
add_fileset_file "hld_ram_short_depth_stitch.sv" SYSTEM_VERILOG PATH "ip/hld_ram_short_depth_stitch.sv"
add_fileset_file "hld_ram_bottom_width_stitch.sv" SYSTEM_VERILOG PATH "ip/hld_ram_bottom_width_stitch.sv"
add_fileset_file "hld_ram_bottom_depth_stitch.sv" SYSTEM_VERILOG PATH "ip/hld_ram_bottom_depth_stitch.sv"
add_fileset_file "hld_ram_lower.sv" SYSTEM_VERILOG PATH "ip/hld_ram_lower.sv"
add_fileset_file "hld_ram_lower_mlab_simple_dual_port.sv" SYSTEM_VERILOG PATH "ip/hld_ram_lower_mlab_simple_dual_port.sv"
add_fileset_file "hld_ram_lower_m20k_simple_dual_port.sv" SYSTEM_VERILOG PATH "ip/hld_ram_lower_m20k_simple_dual_port.sv"
add_fileset_file "hld_ram_lower_m20k_true_dual_port.sv" SYSTEM_VERILOG PATH "ip/hld_ram_lower_m20k_true_dual_port.sv"
add_fileset_file "acl_ic_local_mem_router.v" SYSTEM_VERILOG PATH "ip/acl_ic_local_mem_router.v"
add_fileset_file "acl_mem2x.v" SYSTEM_VERILOG PATH "ip/acl_mem2x.v"
add_fileset_file "atax_internal.v" SYSTEM_VERILOG PATH "atax_internal.v"

#### Simulation fileset
add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL atax_internal
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file "dspba_library_ver.sv" SYSTEM_VERILOG PATH "linux64/lib/dspba/Libraries/sv/base/dspba_library_ver.sv"
add_fileset_file "acl_data_fifo.v" SYSTEM_VERILOG PATH "ip/acl_data_fifo.v"
add_fileset_file "acl_fifo.v" SYSTEM_VERILOG PATH "ip/acl_fifo.v"
add_fileset_file "acl_altera_syncram_wrapped.sv" SYSTEM_VERILOG PATH "ip/acl_altera_syncram_wrapped.sv"
add_fileset_file "acl_scfifo_wrapped.sv" SYSTEM_VERILOG PATH "ip/acl_scfifo_wrapped.sv"
add_fileset_file "acl_ecc_decoder.sv" SYSTEM_VERILOG PATH "ip/acl_ecc_decoder.sv"
add_fileset_file "acl_ecc_encoder.sv" SYSTEM_VERILOG PATH "ip/acl_ecc_encoder.sv"
add_fileset_file "acl_ecc.svh" SYSTEM_VERILOG PATH "ip/acl_ecc.svh"
add_fileset_file "acl_ll_fifo.v" SYSTEM_VERILOG PATH "ip/acl_ll_fifo.v"
add_fileset_file "acl_ll_ram_fifo.v" SYSTEM_VERILOG PATH "ip/acl_ll_ram_fifo.v"
add_fileset_file "acl_valid_fifo_counter.v" SYSTEM_VERILOG PATH "ip/acl_valid_fifo_counter.v"
add_fileset_file "acl_dspba_valid_fifo_counter.v" SYSTEM_VERILOG PATH "ip/acl_dspba_valid_fifo_counter.v"
add_fileset_file "acl_staging_reg.v" SYSTEM_VERILOG PATH "ip/acl_staging_reg.v"
add_fileset_file "hld_fifo.sv" SYSTEM_VERILOG PATH "ip/hld_fifo.sv"
add_fileset_file "acl_mid_speed_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_mid_speed_fifo.sv"
add_fileset_file "acl_latency_one_ram_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_latency_one_ram_fifo.sv"
add_fileset_file "acl_latency_zero_ram_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_latency_zero_ram_fifo.sv"
add_fileset_file "hld_fifo_zero_width.sv" SYSTEM_VERILOG PATH "ip/hld_fifo_zero_width.sv"
add_fileset_file "acl_high_speed_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_high_speed_fifo.sv"
add_fileset_file "acl_low_latency_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_low_latency_fifo.sv"
add_fileset_file "acl_zero_latency_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_zero_latency_fifo.sv"
add_fileset_file "acl_fanout_pipeline.sv" SYSTEM_VERILOG PATH "ip/acl_fanout_pipeline.sv"
add_fileset_file "acl_std_synchronizer_nocut.v" SYSTEM_VERILOG PATH "ip/acl_std_synchronizer_nocut.v"
add_fileset_file "acl_tessellated_incr_decr_threshold.sv" SYSTEM_VERILOG PATH "ip/acl_tessellated_incr_decr_threshold.sv"
add_fileset_file "acl_tessellated_incr_lookahead.sv" SYSTEM_VERILOG PATH "ip/acl_tessellated_incr_lookahead.sv"
add_fileset_file "acl_reset_handler.sv" SYSTEM_VERILOG PATH "ip/acl_reset_handler.sv"
add_fileset_file "acl_lfsr.sv" SYSTEM_VERILOG PATH "ip/acl_lfsr.sv"
add_fileset_file "acl_mlab_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_mlab_fifo.sv"
add_fileset_file "acl_parameter_assert.svh" SYSTEM_VERILOG PATH "ip/acl_parameter_assert.svh"
add_fileset_file "acl_pop.v" SYSTEM_VERILOG PATH "ip/acl_pop.v"
add_fileset_file "acl_push.v" SYSTEM_VERILOG PATH "ip/acl_push.v"
add_fileset_file "acl_token_fifo_counter.v" SYSTEM_VERILOG PATH "ip/acl_token_fifo_counter.v"
add_fileset_file "acl_pipeline.v" SYSTEM_VERILOG PATH "ip/acl_pipeline.v"
add_fileset_file "acl_dspba_buffer.v" SYSTEM_VERILOG PATH "ip/acl_dspba_buffer.v"
add_fileset_file "acl_enable_sink.v" SYSTEM_VERILOG PATH "ip/acl_enable_sink.v"
add_fileset_file "hld_iord.sv" SYSTEM_VERILOG PATH "ip/hld_iord.sv"
add_fileset_file "hld_iord_stall_latency.sv" SYSTEM_VERILOG PATH "ip/hld_iord_stall_latency.sv"
add_fileset_file "hld_iord_stall_valid.sv" SYSTEM_VERILOG PATH "ip/hld_iord_stall_valid.sv"
add_fileset_file "hld_memory_depth_quantization.svh" SYSTEM_VERILOG PATH "ip/hld_memory_depth_quantization.svh"
add_fileset_file "acl_shift_register_no_reset.sv" SYSTEM_VERILOG PATH "ip/acl_shift_register_no_reset.sv"
add_fileset_file "acl_ffwdsrc.v" SYSTEM_VERILOG PATH "ip/acl_ffwdsrc.v"
add_fileset_file "acl_ffwddst.sv" SYSTEM_VERILOG PATH "ip/acl_ffwddst.sv"
add_fileset_file "lsu_top.v" SYSTEM_VERILOG PATH "ip/lsu_top.v"
add_fileset_file "lsu_permute_address.v" SYSTEM_VERILOG PATH "ip/lsu_permute_address.v"
add_fileset_file "lsu_pipelined.v" SYSTEM_VERILOG PATH "ip/lsu_pipelined.v"
add_fileset_file "lsu_enabled.v" SYSTEM_VERILOG PATH "ip/lsu_enabled.v"
add_fileset_file "lsu_basic_coalescer.v" SYSTEM_VERILOG PATH "ip/lsu_basic_coalescer.v"
add_fileset_file "lsu_simple.v" SYSTEM_VERILOG PATH "ip/lsu_simple.v"
add_fileset_file "lsu_streaming.v" SYSTEM_VERILOG PATH "ip/lsu_streaming.v"
add_fileset_file "lsu_burst_master.v" SYSTEM_VERILOG PATH "ip/lsu_burst_master.v"
add_fileset_file "lsu_bursting_load_stores.v" SYSTEM_VERILOG PATH "ip/lsu_bursting_load_stores.v"
add_fileset_file "lsu_non_aligned_write.v" SYSTEM_VERILOG PATH "ip/lsu_non_aligned_write.v"
add_fileset_file "lsu_read_cache.v" SYSTEM_VERILOG PATH "ip/lsu_read_cache.v"
add_fileset_file "lsu_atomic.v" SYSTEM_VERILOG PATH "ip/lsu_atomic.v"
add_fileset_file "lsu_prefetch_block.v" SYSTEM_VERILOG PATH "ip/lsu_prefetch_block.v"
add_fileset_file "lsu_wide_wrapper.v" SYSTEM_VERILOG PATH "ip/lsu_wide_wrapper.v"
add_fileset_file "lsu_streaming_prefetch.v" SYSTEM_VERILOG PATH "ip/lsu_streaming_prefetch.v"
add_fileset_file "acl_aligned_burst_coalesced_lsu.v" SYSTEM_VERILOG PATH "ip/acl_aligned_burst_coalesced_lsu.v"
add_fileset_file "acl_toggle_detect.v" SYSTEM_VERILOG PATH "ip/acl_toggle_detect.v"
add_fileset_file "acl_debug_mem.v" SYSTEM_VERILOG PATH "ip/acl_debug_mem.v"
add_fileset_file "lsu_burst_coalesced_pipelined_write.sv" SYSTEM_VERILOG PATH "ip/lsu_burst_coalesced_pipelined_write.sv"
add_fileset_file "lsu_burst_coalesced_pipelined_read.sv" SYSTEM_VERILOG PATH "ip/lsu_burst_coalesced_pipelined_read.sv"
add_fileset_file "acl_fifo_stall_valid_lookahead.sv" SYSTEM_VERILOG PATH "ip/acl_fifo_stall_valid_lookahead.sv"
add_fileset_file "hld_global_load_store.sv" SYSTEM_VERILOG PATH "ip/hld_global_load_store.sv"
add_fileset_file "hld_lsu.sv" SYSTEM_VERILOG PATH "ip/hld_lsu.sv"
add_fileset_file "hld_lsu_burst_coalescer.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_burst_coalescer.sv"
add_fileset_file "hld_lsu_coalescer_dynamic_timeout.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_coalescer_dynamic_timeout.sv"
add_fileset_file "hld_lsu_data_aligner.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_data_aligner.sv"
add_fileset_file "hld_lsu_read_cache.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_read_cache.sv"
add_fileset_file "hld_lsu_read_data_alignment.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_read_data_alignment.sv"
add_fileset_file "hld_lsu_unaligned_controller.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_unaligned_controller.sv"
add_fileset_file "hld_lsu_word_coalescer.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_word_coalescer.sv"
add_fileset_file "hld_lsu_write_data_alignment.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_write_data_alignment.sv"
add_fileset_file "hld_lsu_write_kernel_downstream.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_write_kernel_downstream.sv"
add_fileset_file "acl_full_detector.v" SYSTEM_VERILOG PATH "ip/acl_full_detector.v"
add_fileset_file "acl_tessellated_incr_decr_decr.sv" SYSTEM_VERILOG PATH "ip/acl_tessellated_incr_decr_decr.sv"
add_fileset_file "hld_iowr.sv" SYSTEM_VERILOG PATH "ip/hld_iowr.sv"
add_fileset_file "hld_iowr_stall_latency.sv" SYSTEM_VERILOG PATH "ip/hld_iowr_stall_latency.sv"
add_fileset_file "hld_iowr_stall_valid.sv" SYSTEM_VERILOG PATH "ip/hld_iowr_stall_valid.sv"
add_fileset_file "acl_loop_limiter.v" SYSTEM_VERILOG PATH "ip/acl_loop_limiter.v"
add_fileset_file "hld_loop_profiler.sv" SYSTEM_VERILOG PATH "ip/hld_loop_profiler.sv"
add_fileset_file "hld_sim_latency_tracker.sv" SYSTEM_VERILOG PATH "ip/hld_sim_latency_tracker.sv"
add_fileset_file "acl_reset_wire.v" SYSTEM_VERILOG PATH "ip/acl_reset_wire.v"
add_fileset_file "atax_function_wrapper.sv" SYSTEM_VERILOG PATH "ip/atax_function_wrapper.sv"
add_fileset_file "atax_function.sv" SYSTEM_VERILOG PATH "ip/atax_function.sv"
add_fileset_file "atax_bb_B0_runOnce.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B0_runOnce.sv"
add_fileset_file "atax_B0_runOnce_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B0_runOnce_branch.sv"
add_fileset_file "atax_B0_runOnce_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B0_runOnce_merge.sv"
add_fileset_file "atax_bb_B0_runOnce_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B0_runOnce_stall_region.sv"
add_fileset_file "atax_B0_runOnce_merge_reg.sv" SYSTEM_VERILOG PATH "ip/atax_B0_runOnce_merge_reg.sv"
add_fileset_file "atax_i_llvm_fpga_pop_token_i1_wt_limpop_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_token_i1_wt_limpop_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_token_i1_wt_limpop_0_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_token_i1_wt_limpop_0_reg.sv"
add_fileset_file "atax_i_llvm_fpga_push_token_i1_wt_limpush_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_token_i1_wt_limpush_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_token_i1_wt_limpush_1_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_token_i1_wt_limpush_1_reg.sv"
add_fileset_file "atax_bb_B10.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B10.sv"
add_fileset_file "atax_B10_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B10_branch.sv"
add_fileset_file "atax_B10_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B10_merge.sv"
add_fileset_file "atax_bb_B10_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B10_stall_region.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_memdep_phi_push20_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_memdep_phi_push20_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_memdep_phi_push20_0_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_memdep_phi_push20_0_reg.sv"
add_fileset_file "atax_bb_B11.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B11.sv"
add_fileset_file "atax_B11_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B11_branch.sv"
add_fileset_file "atax_B11_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B11_merge.sv"
add_fileset_file "atax_bb_B11_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B11_stall_region.sv"
add_fileset_file "atax_bb_B13.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B13.sv"
add_fileset_file "atax_B13_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B13_branch.sv"
add_fileset_file "atax_B13_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B13_merge.sv"
add_fileset_file "atax_bb_B13_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B13_stall_region.sv"
add_fileset_file "atax_i_iowr_bl_return_unnamed_atax21_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_iowr_bl_return_unnamed_atax21_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_push_token_i1_throttle_push_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_token_i1_throttle_push_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_token_i1_throttle_push_1_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_token_i1_throttle_push_1_reg.sv"
add_fileset_file "atax_bb_B2.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B2.sv"
add_fileset_file "atax_B2_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B2_branch.sv"
add_fileset_file "atax_B2_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B2_merge.sv"
add_fileset_file "atax_bb_B2_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B2_stall_region.sv"
add_fileset_file "atax_bb_B5.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B5.sv"
add_fileset_file "atax_B5_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B5_branch.sv"
add_fileset_file "atax_B5_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B5_merge.sv"
add_fileset_file "atax_bb_B5_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B5_stall_region.sv"
add_fileset_file "atax_bb_B6.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B6.sv"
add_fileset_file "atax_B6_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B6_branch.sv"
add_fileset_file "atax_B6_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B6_merge.sv"
add_fileset_file "atax_bb_B6_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B6_stall_region.sv"
add_fileset_file "atax_B6_merge_reg.sv" SYSTEM_VERILOG PATH "ip/atax_B6_merge_reg.sv"
add_fileset_file "atax_i_sfc_s_c0_in_for_cond24_preheader_s_c0_enter14812_atax1.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c0_in_for_cond24_preheader_s_c0_enter14812_atax1.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_c0000r_s_c0_exit156_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_c0000r_s_c0_exit156_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_c0000_atax1_full_detector.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_c0000_atax1_full_detector.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_c0000t156_atax1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_c0000t156_atax1_data_fifo.sv"
add_fileset_file "atax_i_sfc_logic_s_c0_in_for_cond24_preh0000_c0_enter14812_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c0_in_for_cond24_preh0000_c0_enter14812_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_arrayidx28_promoted14_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_arrayidx28_promoted14_0.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going76_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going76_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i32_i_138_pop19_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i32_i_138_pop19_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i7_fpga_indvars_iv36_pop18_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i7_fpga_indvars_iv36_pop18_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notexitcond77_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notexitcond77_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i32_i_138_push19_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i32_i_138_push19_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i7_fpga_indvars_iv36_push18_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i7_fpga_indvars_iv36_push18_0.sv"
add_fileset_file "atax_bb_B7.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B7.sv"
add_fileset_file "atax_B7_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B7_branch.sv"
add_fileset_file "atax_B7_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B7_merge.sv"
add_fileset_file "atax_bb_B7_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B7_stall_region.sv"
add_fileset_file "atax_B7_merge_reg.sv" SYSTEM_VERILOG PATH "ip/atax_B7_merge_reg.sv"
add_fileset_file "atax_i_sfc_s_c0_in_for_body26_s_c0_enter16615_atax1.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c0_in_for_body26_s_c0_enter16615_atax1.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_body26_s_c0_exit178_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_body26_s_c0_exit178_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000_atax1_full_detector.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000_atax1_full_detector.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000t178_atax1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000t178_atax1_data_fifo.sv"
add_fileset_file "atax_i_sfc_logic_s_c0_in_for_body26_s_c0_enter16615_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c0_in_for_body26_s_c0_enter16615_atax0.sv"
add_fileset_file "atax_flt_i_sfc_logic_s_c0_in_for_body26_0000xk5id06uq0cp0jv34qcz.sv" SYSTEM_VERILOG PATH "ip/atax_flt_i_sfc_logic_s_c0_in_for_body26_0000xk5id06uq0cp0jv34qcz.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_16_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_16_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_17_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_17_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going62_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going62_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_f32_add41_pop34_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_f32_add41_pop34_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i1_exitcond38112_pop40_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i1_exitcond38112_pop40_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i1_forked105108_pop37_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i1_forked105108_pop37_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i1_notcmp74114_pop41_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i1_notcmp74114_pop41_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i2_cleanups65_pop36_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i2_cleanups65_pop36_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i32_j_137_pop35_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i32_j_137_pop35_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i64_idxprom27109_pop38_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i64_idxprom27109_pop38_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i7_fpga_indvars_iv30_pop33_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i7_fpga_indvars_iv30_pop33_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_p67f32_arrayidx2812111_pop39_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_p67f32_arrayidx2812111_pop39_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_f32_add41_push34_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_f32_add41_push34_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_exitcond38112_push40_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_exitcond38112_push40_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_forked105108_push37_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_forked105108_push37_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_lastiniteration64_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_lastiniteration64_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notcmp74114_push41_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notcmp74114_push41_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notexitcond72_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notexitcond72_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i2_cleanups65_push36_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i2_cleanups65_push36_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i32_j_137_push35_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i32_j_137_push35_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i64_idxprom27109_push38_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i64_idxprom27109_push38_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i7_fpga_indvars_iv30_push33_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i7_fpga_indvars_iv30_push33_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_p67f32_arrayidx2812111_push39_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_p67f32_arrayidx2812111_push39_0.sv"
add_fileset_file "atax_bb_B8.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B8.sv"
add_fileset_file "atax_B8_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B8_branch.sv"
add_fileset_file "atax_B8_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B8_merge.sv"
add_fileset_file "atax_bb_B8_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B8_stall_region.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i1_memdep_phi_pop20_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i1_memdep_phi_pop20_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i1_memdep_phi_pop20_0_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i1_memdep_phi_pop20_0_reg.sv"
add_fileset_file "atax_i_sfc_s_c0_in_for_inc40_s_c0_enter189_atax3.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c0_in_for_inc40_s_c0_enter189_atax3.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_inc40_s_c0_exit193_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_inc40_s_c0_exit193_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_i0000_atax1_full_detector.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_i0000_atax1_full_detector.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_i0000t193_atax1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_i0000t193_atax1_data_fifo.sv"
add_fileset_file "atax_i_sfc_logic_s_c0_in_for_inc40_s_c0_enter189_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c0_in_for_inc40_s_c0_enter189_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memdep_17233_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memdep_17233_0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_18_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_18_atax0.sv"
add_fileset_file "atax_bb_B9.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B9.sv"
add_fileset_file "atax_B9_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B9_branch.sv"
add_fileset_file "atax_B9_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B9_merge.sv"
add_fileset_file "atax_bb_B9_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B9_stall_region.sv"
add_fileset_file "atax_B9_merge_reg.sv" SYSTEM_VERILOG PATH "ip/atax_B9_merge_reg.sv"
add_fileset_file "atax_i_sfc_s_c0_in_for_body48_s_c0_enter20116_atax1.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c0_in_for_body48_s_c0_enter20116_atax1.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_body48_s_c0_exit213_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_body48_s_c0_exit213_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0001_atax1_full_detector.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0001_atax1_full_detector.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000t213_atax1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000t213_atax1_data_fifo.sv"
add_fileset_file "atax_i_sfc_logic_s_c0_in_for_body48_s_c0_enter20116_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c0_in_for_body48_s_c0_enter20116_atax0.sv"
add_fileset_file "atax_flt_i_sfc_logic_s_c0_in_for_body48_0000xk5id06uq0cp0jv34qcz.sv" SYSTEM_VERILOG PATH "ip/atax_flt_i_sfc_logic_s_c0_in_for_body48_0000xk5id06uq0cp0jv34qcz.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going46_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going46_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_f32_pop48_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_f32_pop48_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i1_exitcond38113_pop46_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i1_exitcond38113_pop46_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i1_memdep_phi_pop20116_pop49_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i1_memdep_phi_pop20116_pop49_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i1_notcmp74115_pop47_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i1_notcmp74115_pop47_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i2_cleanups49_pop44_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i2_cleanups49_pop44_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i32_j_235_pop43_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i32_j_235_pop43_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i5_fpga_indvars_iv33_pop42_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i5_fpga_indvars_iv33_pop42_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i64_idxprom27110_pop45_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i64_idxprom27110_pop45_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_f32_push48_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_f32_push48_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_exitcond38113_push46_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_exitcond38113_push46_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_lastiniteration48_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_lastiniteration48_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_memdep_phi_pop20116_push49_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_memdep_phi_pop20116_push49_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notcmp74115_push47_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notcmp74115_push47_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notexitcond56_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notexitcond56_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i2_cleanups49_push44_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i2_cleanups49_push44_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i32_j_235_push43_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i32_j_235_push43_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i5_fpga_indvars_iv33_push42_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i5_fpga_indvars_iv33_push42_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i64_idxprom27110_push45_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i64_idxprom27110_push45_0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memcoalesce_load_fpgaunique_1510_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memcoalesce_load_fpgaunique_1510_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memcoalesce_load_fpgaunique_1612_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memcoalesce_load_fpgaunique_1612_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memdep_511_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memdep_511_0.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going101_1_sr.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going101_1_sr.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going101_1_valid_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going101_1_valid_fifo.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going46_6_sr.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going46_6_sr.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going46_6_valid_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going46_6_valid_fifo.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going62_6_sr.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going62_6_sr.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going62_6_valid_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going62_6_valid_fifo.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going76_2_sr.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going76_2_sr.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going76_2_valid_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going76_2_valid_fifo.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going83_6_sr.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going83_6_sr.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going83_6_valid_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going83_6_valid_fifo.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going97_0_sr.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going97_0_sr.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going_2_sr.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going_2_sr.sv"
add_fileset_file "atax_loop_limiter_0.sv" SYSTEM_VERILOG PATH "ip/atax_loop_limiter_0.sv"
add_fileset_file "atax_loop_limiter_1.sv" SYSTEM_VERILOG PATH "ip/atax_loop_limiter_1.sv"
add_fileset_file "atax_loop_limiter_2.sv" SYSTEM_VERILOG PATH "ip/atax_loop_limiter_2.sv"
add_fileset_file "atax_loop_limiter_3.sv" SYSTEM_VERILOG PATH "ip/atax_loop_limiter_3.sv"
add_fileset_file "atax_loop_limiter_4.sv" SYSTEM_VERILOG PATH "ip/atax_loop_limiter_4.sv"
add_fileset_file "atax_loop_limiter_5.sv" SYSTEM_VERILOG PATH "ip/atax_loop_limiter_5.sv"
add_fileset_file "atax_bb_B10_sr_0.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B10_sr_0.sv"
add_fileset_file "atax_bb_B11_sr_0.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B11_sr_0.sv"
add_fileset_file "atax_bb_B12.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B12.sv"
add_fileset_file "atax_B12_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B12_branch.sv"
add_fileset_file "atax_B12_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B12_merge.sv"
add_fileset_file "atax_bb_B12_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B12_stall_region.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memdep_18_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memdep_18_0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memdep_20_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memdep_20_0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memdep_22_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memdep_22_0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memdep_24_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memdep_24_0.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going_0.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going_2_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going_2_reg.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i1_memdep_phi21_pop23_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i1_memdep_phi21_pop23_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i1_memdep_phi21_pop23_5_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i1_memdep_phi21_pop23_5_reg.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i1_memdep_phi23_pop24_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i1_memdep_phi23_pop24_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i1_memdep_phi23_pop24_6_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i1_memdep_phi23_pop24_6_reg.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i1_memdep_phi25_pop25_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i1_memdep_phi25_pop25_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i1_memdep_phi25_pop25_7_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i1_memdep_phi25_pop25_7_reg.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i32_i_334_pop22_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i32_i_334_pop22_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i32_i_334_pop22_4_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i32_i_334_pop22_4_reg.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i4_cleanups_pop27_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i4_cleanups_pop27_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i4_cleanups_pop27_1_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i4_cleanups_pop27_1_reg.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i4_initerations_pop26_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i4_initerations_pop26_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i4_initerations_pop26_3_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i4_initerations_pop26_3_reg.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i5_fpga_indvars_iv39_pop21_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i5_fpga_indvars_iv39_pop21_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i5_fpga_indvars_iv39_pop21_8_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i5_fpga_indvars_iv39_pop21_8_reg.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_lastiniteration_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_lastiniteration_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_lastiniteration_36_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_lastiniteration_36_reg.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_memdep_phi21_push23_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_memdep_phi21_push23_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_memdep_phi21_push23_50_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_memdep_phi21_push23_50_reg.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_memdep_phi23_push24_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_memdep_phi23_push24_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_memdep_phi23_push24_51_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_memdep_phi23_push24_51_reg.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_memdep_phi25_push25_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_memdep_phi25_push25_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_memdep_phi25_push25_52_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_memdep_phi25_push25_52_reg.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notexitcond_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notexitcond_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notexitcond_34_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notexitcond_34_reg.sv"
add_fileset_file "atax_i_llvm_fpga_push_i32_i_334_push22_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i32_i_334_push22_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i32_i_334_push22_31_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i32_i_334_push22_31_reg.sv"
add_fileset_file "atax_i_llvm_fpga_push_i4_cleanups_push27_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i4_cleanups_push27_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i4_cleanups_push27_53_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i4_cleanups_push27_53_reg.sv"
add_fileset_file "atax_i_llvm_fpga_push_i4_initerations_push26_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i4_initerations_push26_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i4_initerations_push26_24_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i4_initerations_push26_24_reg.sv"
add_fileset_file "atax_i_llvm_fpga_push_i5_fpga_indvars_iv39_push21_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i5_fpga_indvars_iv39_push21_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i5_fpga_indvars_iv39_push21_35_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i5_fpga_indvars_iv39_push21_35_reg.sv"
add_fileset_file "atax_B12_merge_reg.sv" SYSTEM_VERILOG PATH "ip/atax_B12_merge_reg.sv"
add_fileset_file "atax_i_llvm_fpga_ffwd_dest_s_struct_z4pa0000unnamed_atax20_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_ffwd_dest_s_struct_z4pa0000unnamed_atax20_atax0.sv"
add_fileset_file "atax_i_sfc_s_c0_in_for_body69_s_c0_enter22113_atax38.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c0_in_for_body69_s_c0_enter22113_atax38.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_body69_s_c0_exit228_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_body69_s_c0_exit228_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0002_atax1_full_detector.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0002_atax1_full_detector.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000t228_atax1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000t228_atax1_data_fifo.sv"
add_fileset_file "atax_i_sfc_logic_s_c0_in_for_body69_s_c0_enter22113_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c0_in_for_body69_s_c0_enter22113_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memcoalesce_load_fpgaunique_1713_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memcoalesce_load_fpgaunique_1713_atax0.sv"
add_fileset_file "atax_bb_B12_sr_1.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B12_sr_1.sv"
add_fileset_file "atax_bb_B13_sr_0.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B13_sr_0.sv"
add_fileset_file "atax_bb_B1_start.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B1_start.sv"
add_fileset_file "atax_B1_start_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B1_start_branch.sv"
add_fileset_file "atax_B1_start_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B1_start_merge.sv"
add_fileset_file "atax_bb_B1_start_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B1_start_stall_region.sv"
add_fileset_file "atax_B1_start_merge_reg.sv" SYSTEM_VERILOG PATH "ip/atax_B1_start_merge_reg.sv"
add_fileset_file "atax_i_llvm_fpga_pop_throttle_i1_throttle_pop_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_throttle_i1_throttle_pop_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_throttle_i1_throttle_pop_1_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_throttle_i1_throttle_pop_1_reg.sv"
add_fileset_file "atax_i_iord_bl_call_unnamed_atax2_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_iord_bl_call_unnamed_atax2_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_ffwd_source_s_struct_z40000_unnamed_atax3_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_ffwd_source_s_struct_z40000_unnamed_atax3_atax0.sv"
add_fileset_file "atax_i_sfc_s_c0_in_wt_entry_s_c0_enter11_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c0_in_wt_entry_s_c0_enter11_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_wt_entry_s_c0_exit_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_wt_entry_s_c0_exit_atax0.sv"
add_fileset_file "atax_i_sfc_logic_s_c0_in_wt_entry_s_c0_enter11_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c0_in_wt_entry_s_c0_enter11_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going101_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going101_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notexitcond102_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notexitcond102_0.sv"
add_fileset_file "atax_bb_B2_sr_0.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B2_sr_0.sv"
add_fileset_file "atax_bb_B3.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B3.sv"
add_fileset_file "atax_B3_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B3_branch.sv"
add_fileset_file "atax_B3_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B3_merge.sv"
add_fileset_file "atax_bb_B3_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B3_stall_region.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memdep_15_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memdep_15_0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memdep_16_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memdep_16_0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memdep_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memdep_0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_5_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_5_atax0.sv"
add_fileset_file "atax_readdata_reg_unnamed_5_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_readdata_reg_unnamed_5_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going97_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going97_0.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going97_0_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going97_0_reg.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i32_i_040_pop17_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i32_i_040_pop17_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i32_i_040_pop17_3_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i32_i_040_pop17_3_reg.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i7_fpga_indvars_iv27_pop16_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i7_fpga_indvars_iv27_pop16_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i7_fpga_indvars_iv27_pop16_13_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i7_fpga_indvars_iv27_pop16_13_reg.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notexitcond98_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notexitcond98_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notexitcond98_17_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notexitcond98_17_reg.sv"
add_fileset_file "atax_i_llvm_fpga_push_i32_i_040_push17_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i32_i_040_push17_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i32_i_040_push17_21_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i32_i_040_push17_21_reg.sv"
add_fileset_file "atax_i_llvm_fpga_push_i7_fpga_indvars_iv27_push16_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i7_fpga_indvars_iv27_push16_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i7_fpga_indvars_iv27_push16_19_reg.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i7_fpga_indvars_iv27_push16_19_reg.sv"
add_fileset_file "atax_B3_merge_reg.sv" SYSTEM_VERILOG PATH "ip/atax_B3_merge_reg.sv"
add_fileset_file "atax_i_llvm_fpga_ffwd_dest_s_struct_z4pa0000_unnamed_atax4_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_ffwd_dest_s_struct_z4pa0000_unnamed_atax4_atax0.sv"
add_fileset_file "atax_bb_B3_sr_1.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B3_sr_1.sv"
add_fileset_file "atax_bb_B4.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B4.sv"
add_fileset_file "atax_B4_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B4_branch.sv"
add_fileset_file "atax_B4_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B4_merge.sv"
add_fileset_file "atax_bb_B4_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B4_stall_region.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_10_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_10_atax0.sv"
add_fileset_file "atax_readdata_reg_unnamed_10_atax4.sv" SYSTEM_VERILOG PATH "ip/atax_readdata_reg_unnamed_10_atax4.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_11_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_11_atax0.sv"
add_fileset_file "atax_readdata_reg_unnamed_11_atax5.sv" SYSTEM_VERILOG PATH "ip/atax_readdata_reg_unnamed_11_atax5.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_12_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_12_atax0.sv"
add_fileset_file "atax_readdata_reg_unnamed_12_atax6.sv" SYSTEM_VERILOG PATH "ip/atax_readdata_reg_unnamed_12_atax6.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_13_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_13_atax0.sv"
add_fileset_file "atax_readdata_reg_unnamed_13_atax7.sv" SYSTEM_VERILOG PATH "ip/atax_readdata_reg_unnamed_13_atax7.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_14_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_14_atax0.sv"
add_fileset_file "atax_readdata_reg_unnamed_14_atax8.sv" SYSTEM_VERILOG PATH "ip/atax_readdata_reg_unnamed_14_atax8.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_7_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_7_atax0.sv"
add_fileset_file "atax_readdata_reg_unnamed_7_atax1.sv" SYSTEM_VERILOG PATH "ip/atax_readdata_reg_unnamed_7_atax1.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_8_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_8_atax0.sv"
add_fileset_file "atax_readdata_reg_unnamed_8_atax2.sv" SYSTEM_VERILOG PATH "ip/atax_readdata_reg_unnamed_8_atax2.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_9_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_9_atax0.sv"
add_fileset_file "atax_readdata_reg_unnamed_9_atax3.sv" SYSTEM_VERILOG PATH "ip/atax_readdata_reg_unnamed_9_atax3.sv"
add_fileset_file "atax_B4_merge_reg.sv" SYSTEM_VERILOG PATH "ip/atax_B4_merge_reg.sv"
add_fileset_file "atax_i_sfc_s_c0_in_for_body9_s_c0_enter14314_atax1.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c0_in_for_body9_s_c0_enter14314_atax1.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_body9_s_c0_exit145_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_body9_s_c0_exit145_atax0.sv"
add_fileset_file "atax_i_sfc_logic_s_c0_in_for_body9_s_c0_enter14314_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c0_in_for_body9_s_c0_enter14314_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going83_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going83_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i1_notcmp95107_pop32_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i1_notcmp95107_pop32_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i2_cleanups86_pop30_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i2_cleanups86_pop30_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i32_j_039_pop29_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i32_j_039_pop29_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i4_fpga_indvars_iv_pop28_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i4_fpga_indvars_iv_pop28_0.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i64_idxprom106_pop31_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i64_idxprom106_pop31_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_lastiniteration85_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_lastiniteration85_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notcmp95107_push32_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notcmp95107_push32_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notexitcond93_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notexitcond93_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i2_cleanups86_push30_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i2_cleanups86_push30_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i32_j_039_push29_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i32_j_039_push29_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i4_fpga_indvars_iv_push28_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i4_fpga_indvars_iv_push28_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i64_idxprom106_push31_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i64_idxprom106_push31_0.sv"
add_fileset_file "atax_i_llvm_fpga_ffwd_dest_s_struct_z4pa0000_unnamed_atax6_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_ffwd_dest_s_struct_z4pa0000_unnamed_atax6_atax0.sv"
add_fileset_file "atax_i_sfc_s_c1_in_for_body9_s_c1_enter_atax12.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c1_in_for_body9_s_c1_enter_atax12.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c1_out_for_body9_s_c1_exit_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c1_out_for_body9_s_c1_exit_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c1_out_for_b0000_atax1_full_detector.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c1_out_for_b0000_atax1_full_detector.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c1_out_for_b0000exit_atax1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c1_out_for_b0000exit_atax1_data_fifo.sv"
add_fileset_file "atax_i_sfc_logic_s_c1_in_for_body9_s_c1_enter_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c1_in_for_body9_s_c1_enter_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memdep_19_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memdep_19_0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memdep_8_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memdep_8_0.sv"
add_fileset_file "atax_bb_B4_sr_1.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B4_sr_1.sv"
add_fileset_file "atax_bb_B5_sr_0.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B5_sr_0.sv"
add_fileset_file "atax_bb_B6_sr_1.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B6_sr_1.sv"
add_fileset_file "atax_bb_B7_sr_1.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B7_sr_1.sv"
add_fileset_file "atax_bb_B8_sr_0.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B8_sr_0.sv"
add_fileset_file "atax_bb_B9_sr_1.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B9_sr_1.sv"
add_fileset_file "acl_avm_to_ic.v" SYSTEM_VERILOG PATH "ip/acl_avm_to_ic.v"
add_fileset_file "acl_ic_master_endpoint.v" SYSTEM_VERILOG PATH "ip/acl_ic_master_endpoint.v"
add_fileset_file "acl_arb_intf.v" SYSTEM_VERILOG PATH "ip/acl_arb_intf.v"
add_fileset_file "acl_ic_intf.v" SYSTEM_VERILOG PATH "ip/acl_ic_intf.v"
add_fileset_file "acl_ic_slave_endpoint.v" SYSTEM_VERILOG PATH "ip/acl_ic_slave_endpoint.v"
add_fileset_file "acl_ic_slave_rrp.v" SYSTEM_VERILOG PATH "ip/acl_ic_slave_rrp.v"
add_fileset_file "acl_ic_slave_wrp.v" SYSTEM_VERILOG PATH "ip/acl_ic_slave_wrp.v"
add_fileset_file "acl_arb2.v" SYSTEM_VERILOG PATH "ip/acl_arb2.v"
add_fileset_file "acl_ic_to_avm.v" SYSTEM_VERILOG PATH "ip/acl_ic_to_avm.v"
add_fileset_file "acl_mem1x.v" SYSTEM_VERILOG PATH "ip/acl_mem1x.v"
add_fileset_file "hld_ram.sv" SYSTEM_VERILOG PATH "ip/hld_ram.sv"
add_fileset_file "hld_ram_ecc.sv" SYSTEM_VERILOG PATH "ip/hld_ram_ecc.sv"
add_fileset_file "hld_ram_tall_depth_stitch.sv" SYSTEM_VERILOG PATH "ip/hld_ram_tall_depth_stitch.sv"
add_fileset_file "hld_ram_remaining_width.sv" SYSTEM_VERILOG PATH "ip/hld_ram_remaining_width.sv"
add_fileset_file "hld_ram_bits_per_enable.sv" SYSTEM_VERILOG PATH "ip/hld_ram_bits_per_enable.sv"
add_fileset_file "hld_ram_generic_two_way_depth_stitch.sv" SYSTEM_VERILOG PATH "ip/hld_ram_generic_two_way_depth_stitch.sv"
add_fileset_file "hld_ram_generic_three_way_depth_stitch.sv" SYSTEM_VERILOG PATH "ip/hld_ram_generic_three_way_depth_stitch.sv"
add_fileset_file "hld_ram_short_depth_stitch.sv" SYSTEM_VERILOG PATH "ip/hld_ram_short_depth_stitch.sv"
add_fileset_file "hld_ram_bottom_width_stitch.sv" SYSTEM_VERILOG PATH "ip/hld_ram_bottom_width_stitch.sv"
add_fileset_file "hld_ram_bottom_depth_stitch.sv" SYSTEM_VERILOG PATH "ip/hld_ram_bottom_depth_stitch.sv"
add_fileset_file "hld_ram_lower.sv" SYSTEM_VERILOG PATH "ip/hld_ram_lower.sv"
add_fileset_file "hld_ram_lower_mlab_simple_dual_port.sv" SYSTEM_VERILOG PATH "ip/hld_ram_lower_mlab_simple_dual_port.sv"
add_fileset_file "hld_ram_lower_m20k_simple_dual_port.sv" SYSTEM_VERILOG PATH "ip/hld_ram_lower_m20k_simple_dual_port.sv"
add_fileset_file "hld_ram_lower_m20k_true_dual_port.sv" SYSTEM_VERILOG PATH "ip/hld_ram_lower_m20k_true_dual_port.sv"
add_fileset_file "acl_ic_local_mem_router.v" SYSTEM_VERILOG PATH "ip/acl_ic_local_mem_router.v"
add_fileset_file "acl_mem2x.v" SYSTEM_VERILOG PATH "ip/acl_mem2x.v"
add_fileset_file "atax_internal.v" SYSTEM_VERILOG PATH "atax_internal.v"

#### Primary clock for the component
add_interface clock clock end
set_interface_property clock ENABLED true
set_interface_assignment clock hls.cosim.name {$clock}
add_interface_port clock clock clk input 1

#### Primary reset for the component
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_assignment reset hls.cosim.name {$reset}
add_interface_port reset resetn reset_n input 1

#### Clock at 2x frequency for double pumped regions
add_interface clock2x clock end
set_interface_property clock2x ENABLED true
set_interface_assignment clock2x hls.cosim.name {$clock2x}
add_interface_port clock2x clock2x clk input 1

#### The component invocation protocol interface (call)
add_interface call conduit sink
set_interface_property call associatedClock clock
set_interface_property call associatedReset reset
set_interface_assignment call hls.cosim.name {$call}
add_interface_port call start valid input 1
add_interface_port call busy stall output 1

#### The component return protocol interface (return)
add_interface return conduit source
set_interface_property return associatedClock clock
set_interface_property return associatedReset reset
set_interface_assignment return hls.cosim.name {$return}
add_interface_port return done valid output 1
add_interface_port return stall stall input 1

#### Parameter A interface
add_interface A conduit sink
set_interface_property A associatedClock clock
set_interface_property A associatedReset reset
set_interface_assignment A hls.cosim.name {A}
add_interface_port A A data input 64

#### Parameter x interface
add_interface x conduit sink
set_interface_property x associatedClock clock
set_interface_property x associatedReset reset
set_interface_assignment x hls.cosim.name {x}
add_interface_port x x data input 64

#### Parameter y_out interface
add_interface y_out conduit sink
set_interface_property y_out associatedClock clock
set_interface_property y_out associatedReset reset
set_interface_assignment y_out hls.cosim.name {y_out}
add_interface_port y_out y_out data input 64

#### Master interface avmm_0_rw with base address 0
add_interface avmm_0_rw avalon start
set_interface_property avmm_0_rw ENABLED true
set_interface_property avmm_0_rw associatedClock clock
set_interface_property avmm_0_rw burstOnBurstBoundariesOnly false
set_interface_property avmm_0_rw doStreamReads false
set_interface_property avmm_0_rw doStreamWrites false
set_interface_property avmm_0_rw linewrapBursts false
set_interface_property avmm_0_rw readWaitTime 0
set_interface_property avmm_0_rw readLatency 1
add_interface_port avmm_0_rw avmm_0_rw_address address output 64
add_interface_port avmm_0_rw avmm_0_rw_byteenable byteenable output 8
add_interface_port avmm_0_rw avmm_0_rw_read read output 1
add_interface_port avmm_0_rw avmm_0_rw_readdata readdata input 64
add_interface_port avmm_0_rw avmm_0_rw_write write output 1
add_interface_port avmm_0_rw avmm_0_rw_writedata writedata output 64

#### Quartus settings (QIP strings)
set_qip_strings { "set_instance_assignment -entity \"%entityName%\" -library \"%libraryName%\" -name AUTO_SHIFT_REGISTER_RECOGNITION OFF -to *_NO_SHIFT_REG*"  }
