package require -exact qsys 15.0
set_module_property NAME atax_internal
set_module_property VERSION 1.0
set_module_property INTERNAL true
set_module_property GROUP HLS
set_module_property DISPLAY_NAME atax_internal
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property SUPPORTED_DEVICE_FAMILIES {"Stratix 10"}
set_module_assignment hls.cosim.name {_Z4ataxPA64_fPfS1_}
set_module_assignment hls.compressed.name {atax}

#### Synthesis fileset
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL atax_internal
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file "acl_reset_handler.sv" SYSTEM_VERILOG PATH "ip/acl_reset_handler.sv"
add_fileset_file "dspba_library_ver.sv" SYSTEM_VERILOG PATH "linux64/lib/dspba/Libraries/sv/base/dspba_library_ver.sv"
add_fileset_file "acl_ecc_pkg.sv" SYSTEM_VERILOG PATH "ip/acl_ecc_pkg.sv"
add_fileset_file "acl_data_fifo.v" SYSTEM_VERILOG PATH "ip/acl_data_fifo.v"
add_fileset_file "acl_fifo.v" SYSTEM_VERILOG PATH "ip/acl_fifo.v"
add_fileset_file "acl_altera_syncram_wrapped.sv" SYSTEM_VERILOG PATH "ip/acl_altera_syncram_wrapped.sv"
add_fileset_file "acl_scfifo_wrapped.sv" SYSTEM_VERILOG PATH "ip/acl_scfifo_wrapped.sv"
add_fileset_file "acl_ecc_decoder.sv" SYSTEM_VERILOG PATH "ip/acl_ecc_decoder.sv"
add_fileset_file "acl_ecc_encoder.sv" SYSTEM_VERILOG PATH "ip/acl_ecc_encoder.sv"
add_fileset_file "acl_ll_fifo.v" SYSTEM_VERILOG PATH "ip/acl_ll_fifo.v"
add_fileset_file "acl_ll_ram_fifo.v" SYSTEM_VERILOG PATH "ip/acl_ll_ram_fifo.v"
add_fileset_file "acl_valid_fifo_counter.v" SYSTEM_VERILOG PATH "ip/acl_valid_fifo_counter.v"
add_fileset_file "acl_dspba_valid_fifo_counter.v" SYSTEM_VERILOG PATH "ip/acl_dspba_valid_fifo_counter.v"
add_fileset_file "acl_staging_reg.v" SYSTEM_VERILOG PATH "ip/acl_staging_reg.v"
add_fileset_file "hld_fifo.sv" SYSTEM_VERILOG PATH "ip/hld_fifo.sv"
add_fileset_file "acl_mid_speed_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_mid_speed_fifo.sv"
add_fileset_file "acl_latency_one_ram_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_latency_one_ram_fifo.sv"
add_fileset_file "acl_latency_zero_ram_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_latency_zero_ram_fifo.sv"
add_fileset_file "hld_fifo_zero_width.sv" SYSTEM_VERILOG PATH "ip/hld_fifo_zero_width.sv"
add_fileset_file "acl_high_speed_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_high_speed_fifo.sv"
add_fileset_file "acl_low_latency_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_low_latency_fifo.sv"
add_fileset_file "acl_zero_latency_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_zero_latency_fifo.sv"
add_fileset_file "acl_fanout_pipeline.sv" SYSTEM_VERILOG PATH "ip/acl_fanout_pipeline.sv"
add_fileset_file "acl_std_synchronizer_nocut.v" SYSTEM_VERILOG PATH "ip/acl_std_synchronizer_nocut.v"
add_fileset_file "acl_tessellated_incr_decr_threshold.sv" SYSTEM_VERILOG PATH "ip/acl_tessellated_incr_decr_threshold.sv"
add_fileset_file "acl_tessellated_incr_lookahead.sv" SYSTEM_VERILOG PATH "ip/acl_tessellated_incr_lookahead.sv"
add_fileset_file "acl_lfsr.sv" SYSTEM_VERILOG PATH "ip/acl_lfsr.sv"
add_fileset_file "acl_mlab_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_mlab_fifo.sv"
add_fileset_file "acl_parameter_assert.svh" SYSTEM_VERILOG PATH "ip/acl_parameter_assert.svh"
add_fileset_file "acl_pop_stall_latency.sv" SYSTEM_VERILOG PATH "ip/acl_pop_stall_latency.sv"
add_fileset_file "acl_sync.sv" SYSTEM_VERILOG PATH "ip/acl_sync.sv"
add_fileset_file "acl_desync.sv" SYSTEM_VERILOG PATH "ip/acl_desync.sv"
add_fileset_file "acl_push_stall_latency.sv" SYSTEM_VERILOG PATH "ip/acl_push_stall_latency.sv"
add_fileset_file "acl_dspba_buffer.v" SYSTEM_VERILOG PATH "ip/acl_dspba_buffer.v"
add_fileset_file "acl_fast_pipeline.v" SYSTEM_VERILOG PATH "ip/acl_fast_pipeline.v"
add_fileset_file "acl_push.v" SYSTEM_VERILOG PATH "ip/acl_push.v"
add_fileset_file "acl_token_fifo_counter.v" SYSTEM_VERILOG PATH "ip/acl_token_fifo_counter.v"
add_fileset_file "acl_full_detector.v" SYSTEM_VERILOG PATH "ip/acl_full_detector.v"
add_fileset_file "acl_tessellated_incr_decr_decr.sv" SYSTEM_VERILOG PATH "ip/acl_tessellated_incr_decr_decr.sv"
add_fileset_file "acl_loop_admit.sv" SYSTEM_VERILOG PATH "ip/acl_loop_admit.sv"
add_fileset_file "acl_shift_register_no_reset_dont_merge.sv" SYSTEM_VERILOG PATH "ip/acl_shift_register_no_reset_dont_merge.sv"
add_fileset_file "hld_memory_depth_quantization_pkg.sv" SYSTEM_VERILOG PATH "ip/hld_memory_depth_quantization_pkg.sv"
add_fileset_file "hld_iord.sv" SYSTEM_VERILOG PATH "ip/hld_iord.sv"
add_fileset_file "hld_iord_stall_latency.sv" SYSTEM_VERILOG PATH "ip/hld_iord_stall_latency.sv"
add_fileset_file "hld_iord_stall_valid.sv" SYSTEM_VERILOG PATH "ip/hld_iord_stall_valid.sv"
add_fileset_file "acl_shift_register_no_reset.sv" SYSTEM_VERILOG PATH "ip/acl_shift_register_no_reset.sv"
add_fileset_file "acl_ffwdsrc.v" SYSTEM_VERILOG PATH "ip/acl_ffwdsrc.v"
add_fileset_file "acl_ffwddst.sv" SYSTEM_VERILOG PATH "ip/acl_ffwddst.sv"
add_fileset_file "lsu_top.v" SYSTEM_VERILOG PATH "ip/lsu_top.v"
add_fileset_file "lsu_permute_address.v" SYSTEM_VERILOG PATH "ip/lsu_permute_address.v"
add_fileset_file "lsu_pipelined.v" SYSTEM_VERILOG PATH "ip/lsu_pipelined.v"
add_fileset_file "lsu_enabled.v" SYSTEM_VERILOG PATH "ip/lsu_enabled.v"
add_fileset_file "lsu_basic_coalescer.v" SYSTEM_VERILOG PATH "ip/lsu_basic_coalescer.v"
add_fileset_file "lsu_simple.v" SYSTEM_VERILOG PATH "ip/lsu_simple.v"
add_fileset_file "lsu_streaming.v" SYSTEM_VERILOG PATH "ip/lsu_streaming.v"
add_fileset_file "lsu_burst_master.v" SYSTEM_VERILOG PATH "ip/lsu_burst_master.v"
add_fileset_file "lsu_bursting_load_stores.v" SYSTEM_VERILOG PATH "ip/lsu_bursting_load_stores.v"
add_fileset_file "lsu_non_aligned_write.v" SYSTEM_VERILOG PATH "ip/lsu_non_aligned_write.v"
add_fileset_file "lsu_read_cache.v" SYSTEM_VERILOG PATH "ip/lsu_read_cache.v"
add_fileset_file "lsu_atomic.v" SYSTEM_VERILOG PATH "ip/lsu_atomic.v"
add_fileset_file "lsu_prefetch_block.v" SYSTEM_VERILOG PATH "ip/lsu_prefetch_block.v"
add_fileset_file "lsu_wide_wrapper.v" SYSTEM_VERILOG PATH "ip/lsu_wide_wrapper.v"
add_fileset_file "lsu_streaming_prefetch.v" SYSTEM_VERILOG PATH "ip/lsu_streaming_prefetch.v"
add_fileset_file "acl_aligned_burst_coalesced_lsu.v" SYSTEM_VERILOG PATH "ip/acl_aligned_burst_coalesced_lsu.v"
add_fileset_file "acl_toggle_detect.v" SYSTEM_VERILOG PATH "ip/acl_toggle_detect.v"
add_fileset_file "acl_debug_mem.v" SYSTEM_VERILOG PATH "ip/acl_debug_mem.v"
add_fileset_file "lsu_burst_coalesced_pipelined_write.sv" SYSTEM_VERILOG PATH "ip/lsu_burst_coalesced_pipelined_write.sv"
add_fileset_file "lsu_burst_coalesced_pipelined_read.sv" SYSTEM_VERILOG PATH "ip/lsu_burst_coalesced_pipelined_read.sv"
add_fileset_file "acl_fifo_stall_valid_lookahead.sv" SYSTEM_VERILOG PATH "ip/acl_fifo_stall_valid_lookahead.sv"
add_fileset_file "hld_global_load_store.sv" SYSTEM_VERILOG PATH "ip/hld_global_load_store.sv"
add_fileset_file "hld_lsu.sv" SYSTEM_VERILOG PATH "ip/hld_lsu.sv"
add_fileset_file "hld_lsu_burst_coalescer.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_burst_coalescer.sv"
add_fileset_file "hld_lsu_coalescer_dynamic_timeout.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_coalescer_dynamic_timeout.sv"
add_fileset_file "hld_lsu_data_aligner.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_data_aligner.sv"
add_fileset_file "hld_lsu_read_cache.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_read_cache.sv"
add_fileset_file "hld_lsu_read_data_alignment.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_read_data_alignment.sv"
add_fileset_file "hld_lsu_unaligned_controller.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_unaligned_controller.sv"
add_fileset_file "hld_lsu_word_coalescer.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_word_coalescer.sv"
add_fileset_file "hld_lsu_write_data_alignment.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_write_data_alignment.sv"
add_fileset_file "hld_lsu_write_kernel_downstream.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_write_kernel_downstream.sv"
add_fileset_file "acl_pop_stall_latency_zero_width.sv" SYSTEM_VERILOG PATH "ip/acl_pop_stall_latency_zero_width.sv"
add_fileset_file "acl_push_stall_latency_zero_width.sv" SYSTEM_VERILOG PATH "ip/acl_push_stall_latency_zero_width.sv"
add_fileset_file "hld_iowr.sv" SYSTEM_VERILOG PATH "ip/hld_iowr.sv"
add_fileset_file "hld_iowr_stall_latency.sv" SYSTEM_VERILOG PATH "ip/hld_iowr_stall_latency.sv"
add_fileset_file "hld_iowr_stall_valid.sv" SYSTEM_VERILOG PATH "ip/hld_iowr_stall_valid.sv"
add_fileset_file "hld_loop_profiler.sv" SYSTEM_VERILOG PATH "ip/hld_loop_profiler.sv"
add_fileset_file "hld_sim_latency_tracker.sv" SYSTEM_VERILOG PATH "ip/hld_sim_latency_tracker.sv"
add_fileset_file "atax_function_wrapper.sv" SYSTEM_VERILOG PATH "ip/atax_function_wrapper.sv"
add_fileset_file "atax_function.sv" SYSTEM_VERILOG PATH "ip/atax_function.sv"
add_fileset_file "atax_bb_B0_runOnce.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B0_runOnce.sv"
add_fileset_file "atax_B0_runOnce_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B0_runOnce_branch.sv"
add_fileset_file "atax_B0_runOnce_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B0_runOnce_merge.sv"
add_fileset_file "atax_B0_runOnce_merge_storage.sv" SYSTEM_VERILOG PATH "ip/atax_B0_runOnce_merge_storage.sv"
add_fileset_file "atax_bb_B0_runOnce_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B0_runOnce_stall_region.sv"
add_fileset_file "atax_i_llvm_fpga_pop_token_i1_wt_limpop_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_token_i1_wt_limpop_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_token_i1_wt_limpush_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_token_i1_wt_limpush_0.sv"
add_fileset_file "atax_bb_B10.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B10.sv"
add_fileset_file "atax_B10_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B10_branch.sv"
add_fileset_file "atax_B10_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B10_merge.sv"
add_fileset_file "atax_B10_merge_storage.sv" SYSTEM_VERILOG PATH "ip/atax_B10_merge_storage.sv"
add_fileset_file "atax_bb_B10_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B10_stall_region.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_memdep_phi_push20_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_memdep_phi_push20_0.sv"
add_fileset_file "atax_bb_B11.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B11.sv"
add_fileset_file "atax_B11_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B11_branch.sv"
add_fileset_file "atax_B11_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B11_merge.sv"
add_fileset_file "atax_B11_merge_storage.sv" SYSTEM_VERILOG PATH "ip/atax_B11_merge_storage.sv"
add_fileset_file "atax_bb_B11_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B11_stall_region.sv"
add_fileset_file "atax_bb_B12.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B12.sv"
add_fileset_file "atax_B12_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B12_branch.sv"
add_fileset_file "atax_B12_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B12_merge.sv"
add_fileset_file "atax_B12_merge_storage.sv" SYSTEM_VERILOG PATH "ip/atax_B12_merge_storage.sv"
add_fileset_file "atax_bb_B12_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B12_stall_region.sv"
add_fileset_file "atax_i_sfc_s_c0_in_for_body73_s_c0_enter18714_atax1.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c0_in_for_body73_s_c0_enter18714_atax1.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_body73_s_c0_exit191_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_body73_s_c0_exit191_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0004_atax1_full_detector.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0004_atax1_full_detector.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000t191_atax1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000t191_atax1_data_fifo.sv"
add_fileset_file "atax_i_sfc_logic_s_c0_in_for_body73_s_c0_enter18714_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c0_in_for_body73_s_c0_enter18714_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_dummy_thread_b12_dummy_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_dummy_thread_b12_dummy_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_ffwd_dest_p1024f32_y_out4425_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_ffwd_dest_p1024f32_y_out4425_0.sv"
add_fileset_file "atax_i_llvm_fpga_forked_b12_forked_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_forked_b12_forked_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memdep_7_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memdep_7_0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_16_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_16_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notexitcond_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notexitcond_0.sv"
add_fileset_file "atax_bb_B13.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B13.sv"
add_fileset_file "atax_B13_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B13_branch.sv"
add_fileset_file "atax_B13_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B13_merge.sv"
add_fileset_file "atax_B13_merge_storage.sv" SYSTEM_VERILOG PATH "ip/atax_B13_merge_storage.sv"
add_fileset_file "atax_bb_B13_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B13_stall_region.sv"
add_fileset_file "atax_i_iowr_bl_return_unnamed_atax17_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_iowr_bl_return_unnamed_atax17_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_push_token_i1_throttle_push_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_token_i1_throttle_push_0.sv"
add_fileset_file "atax_bb_B1_start.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B1_start.sv"
add_fileset_file "atax_B1_start_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B1_start_branch.sv"
add_fileset_file "atax_B1_start_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B1_start_merge.sv"
add_fileset_file "atax_B1_start_merge_storage.sv" SYSTEM_VERILOG PATH "ip/atax_B1_start_merge_storage.sv"
add_fileset_file "atax_bb_B1_start_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B1_start_stall_region.sv"
add_fileset_file "atax_i_llvm_fpga_pop_throttle_i1_throttle_pop_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_throttle_i1_throttle_pop_0.sv"
add_fileset_file "atax_i_iord_bl_call_unnamed_atax1_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_iord_bl_call_unnamed_atax1_atax0.sv"
add_fileset_file "atax_i_sfc_s_c0_in_wt_entry_s_c0_enter11_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c0_in_wt_entry_s_c0_enter11_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_wt_entry_s_c0_exit_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_wt_entry_s_c0_exit_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_wt_en0000_atax1_full_detector.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_wt_en0000_atax1_full_detector.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_wt_en0000exit_atax1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_wt_en0000exit_atax1_data_fifo.sv"
add_fileset_file "atax_i_sfc_logic_s_c0_in_wt_entry_s_c0_enter11_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c0_in_wt_entry_s_c0_enter11_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_dummy_thread_b1_start_dummy_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_dummy_thread_b1_start_dummy_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_forked_b1_start_forked_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_forked_b1_start_forked_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going52_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going52_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notexitcond53_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notexitcond53_0.sv"
add_fileset_file "atax_i_sfc_s_c1_in_wt_entry_s_c1_enter_atax4.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c1_in_wt_entry_s_c1_enter_atax4.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c1_out_wt_entry_s_c1_exit_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c1_out_wt_entry_s_c1_exit_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c1_out_wt_en0000_atax1_full_detector.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c1_out_wt_en0000_atax1_full_detector.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c1_out_wt_en0000exit_atax1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c1_out_wt_en0000exit_atax1_data_fifo.sv"
add_fileset_file "atax_i_sfc_logic_s_c1_in_wt_entry_s_c1_enter_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c1_in_wt_entry_s_c1_enter_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_ffwd_source_p1024a64f32_unnamed_2_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_ffwd_source_p1024a64f32_unnamed_2_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_ffwd_source_p1024f32_unnamed_3_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_ffwd_source_p1024f32_unnamed_3_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_ffwd_source_p1024f32_unnamed_4_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_ffwd_source_p1024f32_unnamed_4_atax0.sv"
add_fileset_file "atax_bb_B2.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B2.sv"
add_fileset_file "atax_B2_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B2_branch.sv"
add_fileset_file "atax_B2_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B2_merge.sv"
add_fileset_file "atax_B2_merge_storage.sv" SYSTEM_VERILOG PATH "ip/atax_B2_merge_storage.sv"
add_fileset_file "atax_bb_B2_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B2_stall_region.sv"
add_fileset_file "atax_bb_B3.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B3.sv"
add_fileset_file "atax_B3_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B3_branch.sv"
add_fileset_file "atax_B3_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B3_merge.sv"
add_fileset_file "atax_B3_merge_storage.sv" SYSTEM_VERILOG PATH "ip/atax_B3_merge_storage.sv"
add_fileset_file "atax_bb_B3_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B3_stall_region.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_7_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_7_atax0.sv"
add_fileset_file "atax_i_sfc_s_c0_in_for_body_s_c0_enter9612_atax1.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c0_in_for_body_s_c0_enter9612_atax1.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_body_s_c0_exit98_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_body_s_c0_exit98_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000_atax1_full_detector.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000_atax1_full_detector.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000it98_atax1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000it98_atax1_data_fifo.sv"
add_fileset_file "atax_i_sfc_logic_s_c0_in_for_body_s_c0_enter9612_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c0_in_for_body_s_c0_enter9612_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_dummy_thread_b3_dummy_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_dummy_thread_b3_dummy_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_ffwd_dest_p1024f32_x4324_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_ffwd_dest_p1024f32_x4324_0.sv"
add_fileset_file "atax_i_llvm_fpga_forked_b3_forked_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_forked_b3_forked_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memdep_2_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memdep_2_0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memdep_3_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memdep_3_0.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going48_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going48_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notexitcond49_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notexitcond49_0.sv"
add_fileset_file "atax_i_sfc_s_c1_in_for_body_s_c1_enter101_atax5.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c1_in_for_body_s_c1_enter101_atax5.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c1_out_for_body_s_c1_exit103_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c1_out_for_body_s_c1_exit103_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c1_out_for_b0000_atax1_full_detector.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c1_out_for_b0000_atax1_full_detector.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c1_out_for_b0000t103_atax1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c1_out_for_b0000t103_atax1_data_fifo.sv"
add_fileset_file "atax_i_sfc_logic_s_c1_in_for_body_s_c1_enter101_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c1_in_for_body_s_c1_enter101_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memdep_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memdep_0.sv"
add_fileset_file "atax_bb_B4.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B4.sv"
add_fileset_file "atax_B4_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B4_branch.sv"
add_fileset_file "atax_B4_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B4_merge.sv"
add_fileset_file "atax_B4_merge_storage.sv" SYSTEM_VERILOG PATH "ip/atax_B4_merge_storage.sv"
add_fileset_file "atax_bb_B4_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B4_stall_region.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_9_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_9_atax0.sv"
add_fileset_file "atax_i_sfc_s_c0_in_for_body13_s_c0_enter10515_atax3.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c0_in_for_body13_s_c0_enter10515_atax3.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_body13_s_c0_exit111_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_body13_s_c0_exit111_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0001_atax1_full_detector.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0001_atax1_full_detector.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000t111_atax1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000t111_atax1_data_fifo.sv"
add_fileset_file "atax_i_sfc_logic_s_c0_in_for_body13_s_c0_enter10515_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c0_in_for_body13_s_c0_enter10515_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_dummy_thread_b4_dummy_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_dummy_thread_b4_dummy_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_ffwd_dest_p1024a64f32_a4223_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_ffwd_dest_p1024a64f32_a4223_0.sv"
add_fileset_file "atax_i_llvm_fpga_forked_b4_forked_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_forked_b4_forked_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going43_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going43_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notexitcond44_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notexitcond44_0.sv"
add_fileset_file "atax_i_sfc_s_c1_in_for_body13_s_c1_enter118_atax7.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c1_in_for_body13_s_c1_enter118_atax7.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c1_out_for_body13_s_c1_exit121_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c1_out_for_body13_s_c1_exit121_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c1_out_for_b0001_atax1_full_detector.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c1_out_for_b0001_atax1_full_detector.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c1_out_for_b0000t121_atax1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c1_out_for_b0000t121_atax1_data_fifo.sv"
add_fileset_file "atax_i_sfc_logic_s_c1_in_for_body13_s_c1_enter118_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c1_in_for_body13_s_c1_enter118_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memdep_4_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memdep_4_0.sv"
add_fileset_file "atax_bb_B5.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B5.sv"
add_fileset_file "atax_B5_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B5_branch.sv"
add_fileset_file "atax_B5_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B5_merge.sv"
add_fileset_file "atax_B5_merge_storage.sv" SYSTEM_VERILOG PATH "ip/atax_B5_merge_storage.sv"
add_fileset_file "atax_bb_B5_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B5_stall_region.sv"
add_fileset_file "atax_bb_B6.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B6.sv"
add_fileset_file "atax_B6_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B6_branch.sv"
add_fileset_file "atax_B6_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B6_merge.sv"
add_fileset_file "atax_B6_merge_storage.sv" SYSTEM_VERILOG PATH "ip/atax_B6_merge_storage.sv"
add_fileset_file "atax_bb_B6_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B6_stall_region.sv"
add_fileset_file "atax_i_sfc_s_c0_in_for_cond28_preheader_s_c0_enter12313_atax1.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c0_in_for_cond28_preheader_s_c0_enter12313_atax1.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_c0000r_s_c0_exit130_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_c0000r_s_c0_exit130_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_c0000_atax1_full_detector.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_c0000_atax1_full_detector.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_c0000t130_atax1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_c0000t130_atax1_data_fifo.sv"
add_fileset_file "atax_i_sfc_logic_s_c0_in_for_cond28_preh0000_c0_enter12313_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c0_in_for_cond28_preh0000_c0_enter12313_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_dummy_thread_b6_dummy_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_dummy_thread_b6_dummy_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_forked_b6_forked_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_forked_b6_forked_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_arrayidx32_promoted1_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_arrayidx32_promoted1_0.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going38_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going38_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notexitcond39_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notexitcond39_0.sv"
add_fileset_file "atax_bb_B7.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B7.sv"
add_fileset_file "atax_B7_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B7_branch.sv"
add_fileset_file "atax_B7_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B7_merge.sv"
add_fileset_file "atax_B7_merge_storage.sv" SYSTEM_VERILOG PATH "ip/atax_B7_merge_storage.sv"
add_fileset_file "atax_bb_B7_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B7_stall_region.sv"
add_fileset_file "atax_i_sfc_s_c0_in_for_body30_s_c0_enter13916_atax7.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c0_in_for_body30_s_c0_enter13916_atax7.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_body30_s_c0_exit149_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_body30_s_c0_exit149_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0002_atax1_full_detector.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0002_atax1_full_detector.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000t149_atax1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000t149_atax1_data_fifo.sv"
add_fileset_file "atax_i_sfc_logic_s_c0_in_for_body30_s_c0_enter13916_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c0_in_for_body30_s_c0_enter13916_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_dummy_thread_b7_dummy_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_dummy_thread_b7_dummy_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_forked_b7_forked_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_forked_b7_forked_atax0.sv"
add_fileset_file "atax_flt_i_sfc_logic_s_c0_in_for_body30_0000xk5id06uq0cp0jv34qcz.sv" SYSTEM_VERILOG PATH "ip/atax_flt_i_sfc_logic_s_c0_in_for_body30_0000xk5id06uq0cp0jv34qcz.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_11_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_11_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_12_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_12_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going33_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going33_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notexitcond34_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notexitcond34_0.sv"
add_fileset_file "atax_bb_B8.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B8.sv"
add_fileset_file "atax_B8_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B8_branch.sv"
add_fileset_file "atax_B8_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B8_merge.sv"
add_fileset_file "atax_B8_merge_storage.sv" SYSTEM_VERILOG PATH "ip/atax_B8_merge_storage.sv"
add_fileset_file "atax_bb_B8_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B8_stall_region.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i1_memdep_phi_pop20_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i1_memdep_phi_pop20_0.sv"
add_fileset_file "atax_i_sfc_s_c0_in_for_inc44_s_c0_enter158_atax3.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c0_in_for_inc44_s_c0_enter158_atax3.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_inc44_s_c0_exit161_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_inc44_s_c0_exit161_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_i0000_atax1_full_detector.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_i0000_atax1_full_detector.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_i0000t161_atax1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_i0000t161_atax1_data_fifo.sv"
add_fileset_file "atax_i_sfc_logic_s_c0_in_for_inc44_s_c0_enter158_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c0_in_for_inc44_s_c0_enter158_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memdep_5_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memdep_5_0.sv"
add_fileset_file "atax_bb_B9.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B9.sv"
add_fileset_file "atax_B9_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B9_branch.sv"
add_fileset_file "atax_B9_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B9_merge.sv"
add_fileset_file "atax_B9_merge_storage.sv" SYSTEM_VERILOG PATH "ip/atax_B9_merge_storage.sv"
add_fileset_file "atax_bb_B9_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B9_stall_region.sv"
add_fileset_file "atax_i_sfc_s_c0_in_for_body52_s_c0_enter16817_atax6.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c0_in_for_body52_s_c0_enter16817_atax6.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_body52_s_c0_exit180_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_body52_s_c0_exit180_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0003_atax1_full_detector.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0003_atax1_full_detector.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000t180_atax1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000t180_atax1_data_fifo.sv"
add_fileset_file "atax_i_sfc_logic_s_c0_in_for_body52_s_c0_enter16817_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c0_in_for_body52_s_c0_enter16817_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_dummy_thread_b9_dummy_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_dummy_thread_b9_dummy_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_forked_b9_forked_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_forked_b9_forked_atax0.sv"
add_fileset_file "atax_flt_i_sfc_logic_s_c0_in_for_body52_0000xk5id06uq0cp0jv34qcz.sv" SYSTEM_VERILOG PATH "ip/atax_flt_i_sfc_logic_s_c0_in_for_body52_0000xk5id06uq0cp0jv34qcz.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memdep_6_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memdep_6_0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_14_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_14_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_15_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_15_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going28_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going28_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notexitcond29_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notexitcond29_0.sv"
add_fileset_file "atax_start_pulse.sv" SYSTEM_VERILOG PATH "ip/atax_start_pulse.sv"
add_fileset_file "atax_wait_pulse_extender_inst.sv" SYSTEM_VERILOG PATH "ip/atax_wait_pulse_extender_inst.sv"
add_fileset_file "acl_avm_to_ic.v" SYSTEM_VERILOG PATH "ip/acl_avm_to_ic.v"
add_fileset_file "acl_ic_master_endpoint.v" SYSTEM_VERILOG PATH "ip/acl_ic_master_endpoint.v"
add_fileset_file "acl_arb_intf.v" SYSTEM_VERILOG PATH "ip/acl_arb_intf.v"
add_fileset_file "acl_ic_intf.v" SYSTEM_VERILOG PATH "ip/acl_ic_intf.v"
add_fileset_file "acl_ic_slave_endpoint.v" SYSTEM_VERILOG PATH "ip/acl_ic_slave_endpoint.v"
add_fileset_file "acl_ic_slave_rrp.v" SYSTEM_VERILOG PATH "ip/acl_ic_slave_rrp.v"
add_fileset_file "acl_ic_slave_wrp.v" SYSTEM_VERILOG PATH "ip/acl_ic_slave_wrp.v"
add_fileset_file "acl_arb2.v" SYSTEM_VERILOG PATH "ip/acl_arb2.v"
add_fileset_file "acl_ic_to_avm.v" SYSTEM_VERILOG PATH "ip/acl_ic_to_avm.v"
add_fileset_file "acl_mem1x.v" SYSTEM_VERILOG PATH "ip/acl_mem1x.v"
add_fileset_file "hld_ram.sv" SYSTEM_VERILOG PATH "ip/hld_ram.sv"
add_fileset_file "hld_ram_ecc.sv" SYSTEM_VERILOG PATH "ip/hld_ram_ecc.sv"
add_fileset_file "hld_ram_tall_depth_stitch.sv" SYSTEM_VERILOG PATH "ip/hld_ram_tall_depth_stitch.sv"
add_fileset_file "hld_ram_remaining_width.sv" SYSTEM_VERILOG PATH "ip/hld_ram_remaining_width.sv"
add_fileset_file "hld_ram_bits_per_enable.sv" SYSTEM_VERILOG PATH "ip/hld_ram_bits_per_enable.sv"
add_fileset_file "hld_ram_generic_two_way_depth_stitch.sv" SYSTEM_VERILOG PATH "ip/hld_ram_generic_two_way_depth_stitch.sv"
add_fileset_file "hld_ram_generic_three_way_depth_stitch.sv" SYSTEM_VERILOG PATH "ip/hld_ram_generic_three_way_depth_stitch.sv"
add_fileset_file "hld_ram_short_depth_stitch.sv" SYSTEM_VERILOG PATH "ip/hld_ram_short_depth_stitch.sv"
add_fileset_file "hld_ram_bottom_width_stitch.sv" SYSTEM_VERILOG PATH "ip/hld_ram_bottom_width_stitch.sv"
add_fileset_file "hld_ram_bottom_depth_stitch.sv" SYSTEM_VERILOG PATH "ip/hld_ram_bottom_depth_stitch.sv"
add_fileset_file "hld_ram_lower.sv" SYSTEM_VERILOG PATH "ip/hld_ram_lower.sv"
add_fileset_file "hld_ram_lower_mlab_simple_dual_port.sv" SYSTEM_VERILOG PATH "ip/hld_ram_lower_mlab_simple_dual_port.sv"
add_fileset_file "hld_ram_lower_m20k_simple_dual_port.sv" SYSTEM_VERILOG PATH "ip/hld_ram_lower_m20k_simple_dual_port.sv"
add_fileset_file "hld_ram_lower_m20k_true_dual_port.sv" SYSTEM_VERILOG PATH "ip/hld_ram_lower_m20k_true_dual_port.sv"
add_fileset_file "acl_ic_local_mem_router.v" SYSTEM_VERILOG PATH "ip/acl_ic_local_mem_router.v"
add_fileset_file "atax_internal.v" SYSTEM_VERILOG PATH "atax_internal.v"

#### Simulation fileset
add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL atax_internal
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file "acl_reset_handler.sv" SYSTEM_VERILOG PATH "ip/acl_reset_handler.sv"
add_fileset_file "dspba_library_ver.sv" SYSTEM_VERILOG PATH "linux64/lib/dspba/Libraries/sv/base/dspba_library_ver.sv"
add_fileset_file "acl_ecc_pkg.sv" SYSTEM_VERILOG PATH "ip/acl_ecc_pkg.sv"
add_fileset_file "acl_data_fifo.v" SYSTEM_VERILOG PATH "ip/acl_data_fifo.v"
add_fileset_file "acl_fifo.v" SYSTEM_VERILOG PATH "ip/acl_fifo.v"
add_fileset_file "acl_altera_syncram_wrapped.sv" SYSTEM_VERILOG PATH "ip/acl_altera_syncram_wrapped.sv"
add_fileset_file "acl_scfifo_wrapped.sv" SYSTEM_VERILOG PATH "ip/acl_scfifo_wrapped.sv"
add_fileset_file "acl_ecc_decoder.sv" SYSTEM_VERILOG PATH "ip/acl_ecc_decoder.sv"
add_fileset_file "acl_ecc_encoder.sv" SYSTEM_VERILOG PATH "ip/acl_ecc_encoder.sv"
add_fileset_file "acl_ll_fifo.v" SYSTEM_VERILOG PATH "ip/acl_ll_fifo.v"
add_fileset_file "acl_ll_ram_fifo.v" SYSTEM_VERILOG PATH "ip/acl_ll_ram_fifo.v"
add_fileset_file "acl_valid_fifo_counter.v" SYSTEM_VERILOG PATH "ip/acl_valid_fifo_counter.v"
add_fileset_file "acl_dspba_valid_fifo_counter.v" SYSTEM_VERILOG PATH "ip/acl_dspba_valid_fifo_counter.v"
add_fileset_file "acl_staging_reg.v" SYSTEM_VERILOG PATH "ip/acl_staging_reg.v"
add_fileset_file "hld_fifo.sv" SYSTEM_VERILOG PATH "ip/hld_fifo.sv"
add_fileset_file "acl_mid_speed_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_mid_speed_fifo.sv"
add_fileset_file "acl_latency_one_ram_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_latency_one_ram_fifo.sv"
add_fileset_file "acl_latency_zero_ram_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_latency_zero_ram_fifo.sv"
add_fileset_file "hld_fifo_zero_width.sv" SYSTEM_VERILOG PATH "ip/hld_fifo_zero_width.sv"
add_fileset_file "acl_high_speed_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_high_speed_fifo.sv"
add_fileset_file "acl_low_latency_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_low_latency_fifo.sv"
add_fileset_file "acl_zero_latency_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_zero_latency_fifo.sv"
add_fileset_file "acl_fanout_pipeline.sv" SYSTEM_VERILOG PATH "ip/acl_fanout_pipeline.sv"
add_fileset_file "acl_std_synchronizer_nocut.v" SYSTEM_VERILOG PATH "ip/acl_std_synchronizer_nocut.v"
add_fileset_file "acl_tessellated_incr_decr_threshold.sv" SYSTEM_VERILOG PATH "ip/acl_tessellated_incr_decr_threshold.sv"
add_fileset_file "acl_tessellated_incr_lookahead.sv" SYSTEM_VERILOG PATH "ip/acl_tessellated_incr_lookahead.sv"
add_fileset_file "acl_lfsr.sv" SYSTEM_VERILOG PATH "ip/acl_lfsr.sv"
add_fileset_file "acl_mlab_fifo.sv" SYSTEM_VERILOG PATH "ip/acl_mlab_fifo.sv"
add_fileset_file "acl_parameter_assert.svh" SYSTEM_VERILOG PATH "ip/acl_parameter_assert.svh"
add_fileset_file "acl_pop_stall_latency.sv" SYSTEM_VERILOG PATH "ip/acl_pop_stall_latency.sv"
add_fileset_file "acl_sync.sv" SYSTEM_VERILOG PATH "ip/acl_sync.sv"
add_fileset_file "acl_desync.sv" SYSTEM_VERILOG PATH "ip/acl_desync.sv"
add_fileset_file "acl_push_stall_latency.sv" SYSTEM_VERILOG PATH "ip/acl_push_stall_latency.sv"
add_fileset_file "acl_dspba_buffer.v" SYSTEM_VERILOG PATH "ip/acl_dspba_buffer.v"
add_fileset_file "acl_fast_pipeline.v" SYSTEM_VERILOG PATH "ip/acl_fast_pipeline.v"
add_fileset_file "acl_push.v" SYSTEM_VERILOG PATH "ip/acl_push.v"
add_fileset_file "acl_token_fifo_counter.v" SYSTEM_VERILOG PATH "ip/acl_token_fifo_counter.v"
add_fileset_file "acl_full_detector.v" SYSTEM_VERILOG PATH "ip/acl_full_detector.v"
add_fileset_file "acl_tessellated_incr_decr_decr.sv" SYSTEM_VERILOG PATH "ip/acl_tessellated_incr_decr_decr.sv"
add_fileset_file "acl_loop_admit.sv" SYSTEM_VERILOG PATH "ip/acl_loop_admit.sv"
add_fileset_file "acl_shift_register_no_reset_dont_merge.sv" SYSTEM_VERILOG PATH "ip/acl_shift_register_no_reset_dont_merge.sv"
add_fileset_file "hld_memory_depth_quantization_pkg.sv" SYSTEM_VERILOG PATH "ip/hld_memory_depth_quantization_pkg.sv"
add_fileset_file "hld_iord.sv" SYSTEM_VERILOG PATH "ip/hld_iord.sv"
add_fileset_file "hld_iord_stall_latency.sv" SYSTEM_VERILOG PATH "ip/hld_iord_stall_latency.sv"
add_fileset_file "hld_iord_stall_valid.sv" SYSTEM_VERILOG PATH "ip/hld_iord_stall_valid.sv"
add_fileset_file "acl_shift_register_no_reset.sv" SYSTEM_VERILOG PATH "ip/acl_shift_register_no_reset.sv"
add_fileset_file "acl_ffwdsrc.v" SYSTEM_VERILOG PATH "ip/acl_ffwdsrc.v"
add_fileset_file "acl_ffwddst.sv" SYSTEM_VERILOG PATH "ip/acl_ffwddst.sv"
add_fileset_file "lsu_top.v" SYSTEM_VERILOG PATH "ip/lsu_top.v"
add_fileset_file "lsu_permute_address.v" SYSTEM_VERILOG PATH "ip/lsu_permute_address.v"
add_fileset_file "lsu_pipelined.v" SYSTEM_VERILOG PATH "ip/lsu_pipelined.v"
add_fileset_file "lsu_enabled.v" SYSTEM_VERILOG PATH "ip/lsu_enabled.v"
add_fileset_file "lsu_basic_coalescer.v" SYSTEM_VERILOG PATH "ip/lsu_basic_coalescer.v"
add_fileset_file "lsu_simple.v" SYSTEM_VERILOG PATH "ip/lsu_simple.v"
add_fileset_file "lsu_streaming.v" SYSTEM_VERILOG PATH "ip/lsu_streaming.v"
add_fileset_file "lsu_burst_master.v" SYSTEM_VERILOG PATH "ip/lsu_burst_master.v"
add_fileset_file "lsu_bursting_load_stores.v" SYSTEM_VERILOG PATH "ip/lsu_bursting_load_stores.v"
add_fileset_file "lsu_non_aligned_write.v" SYSTEM_VERILOG PATH "ip/lsu_non_aligned_write.v"
add_fileset_file "lsu_read_cache.v" SYSTEM_VERILOG PATH "ip/lsu_read_cache.v"
add_fileset_file "lsu_atomic.v" SYSTEM_VERILOG PATH "ip/lsu_atomic.v"
add_fileset_file "lsu_prefetch_block.v" SYSTEM_VERILOG PATH "ip/lsu_prefetch_block.v"
add_fileset_file "lsu_wide_wrapper.v" SYSTEM_VERILOG PATH "ip/lsu_wide_wrapper.v"
add_fileset_file "lsu_streaming_prefetch.v" SYSTEM_VERILOG PATH "ip/lsu_streaming_prefetch.v"
add_fileset_file "acl_aligned_burst_coalesced_lsu.v" SYSTEM_VERILOG PATH "ip/acl_aligned_burst_coalesced_lsu.v"
add_fileset_file "acl_toggle_detect.v" SYSTEM_VERILOG PATH "ip/acl_toggle_detect.v"
add_fileset_file "acl_debug_mem.v" SYSTEM_VERILOG PATH "ip/acl_debug_mem.v"
add_fileset_file "lsu_burst_coalesced_pipelined_write.sv" SYSTEM_VERILOG PATH "ip/lsu_burst_coalesced_pipelined_write.sv"
add_fileset_file "lsu_burst_coalesced_pipelined_read.sv" SYSTEM_VERILOG PATH "ip/lsu_burst_coalesced_pipelined_read.sv"
add_fileset_file "acl_fifo_stall_valid_lookahead.sv" SYSTEM_VERILOG PATH "ip/acl_fifo_stall_valid_lookahead.sv"
add_fileset_file "hld_global_load_store.sv" SYSTEM_VERILOG PATH "ip/hld_global_load_store.sv"
add_fileset_file "hld_lsu.sv" SYSTEM_VERILOG PATH "ip/hld_lsu.sv"
add_fileset_file "hld_lsu_burst_coalescer.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_burst_coalescer.sv"
add_fileset_file "hld_lsu_coalescer_dynamic_timeout.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_coalescer_dynamic_timeout.sv"
add_fileset_file "hld_lsu_data_aligner.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_data_aligner.sv"
add_fileset_file "hld_lsu_read_cache.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_read_cache.sv"
add_fileset_file "hld_lsu_read_data_alignment.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_read_data_alignment.sv"
add_fileset_file "hld_lsu_unaligned_controller.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_unaligned_controller.sv"
add_fileset_file "hld_lsu_word_coalescer.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_word_coalescer.sv"
add_fileset_file "hld_lsu_write_data_alignment.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_write_data_alignment.sv"
add_fileset_file "hld_lsu_write_kernel_downstream.sv" SYSTEM_VERILOG PATH "ip/hld_lsu_write_kernel_downstream.sv"
add_fileset_file "acl_pop_stall_latency_zero_width.sv" SYSTEM_VERILOG PATH "ip/acl_pop_stall_latency_zero_width.sv"
add_fileset_file "acl_push_stall_latency_zero_width.sv" SYSTEM_VERILOG PATH "ip/acl_push_stall_latency_zero_width.sv"
add_fileset_file "hld_iowr.sv" SYSTEM_VERILOG PATH "ip/hld_iowr.sv"
add_fileset_file "hld_iowr_stall_latency.sv" SYSTEM_VERILOG PATH "ip/hld_iowr_stall_latency.sv"
add_fileset_file "hld_iowr_stall_valid.sv" SYSTEM_VERILOG PATH "ip/hld_iowr_stall_valid.sv"
add_fileset_file "hld_loop_profiler.sv" SYSTEM_VERILOG PATH "ip/hld_loop_profiler.sv"
add_fileset_file "hld_sim_latency_tracker.sv" SYSTEM_VERILOG PATH "ip/hld_sim_latency_tracker.sv"
add_fileset_file "atax_function_wrapper.sv" SYSTEM_VERILOG PATH "ip/atax_function_wrapper.sv"
add_fileset_file "atax_function.sv" SYSTEM_VERILOG PATH "ip/atax_function.sv"
add_fileset_file "atax_bb_B0_runOnce.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B0_runOnce.sv"
add_fileset_file "atax_B0_runOnce_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B0_runOnce_branch.sv"
add_fileset_file "atax_B0_runOnce_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B0_runOnce_merge.sv"
add_fileset_file "atax_B0_runOnce_merge_storage.sv" SYSTEM_VERILOG PATH "ip/atax_B0_runOnce_merge_storage.sv"
add_fileset_file "atax_bb_B0_runOnce_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B0_runOnce_stall_region.sv"
add_fileset_file "atax_i_llvm_fpga_pop_token_i1_wt_limpop_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_token_i1_wt_limpop_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_token_i1_wt_limpush_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_token_i1_wt_limpush_0.sv"
add_fileset_file "atax_bb_B10.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B10.sv"
add_fileset_file "atax_B10_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B10_branch.sv"
add_fileset_file "atax_B10_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B10_merge.sv"
add_fileset_file "atax_B10_merge_storage.sv" SYSTEM_VERILOG PATH "ip/atax_B10_merge_storage.sv"
add_fileset_file "atax_bb_B10_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B10_stall_region.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_memdep_phi_push20_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_memdep_phi_push20_0.sv"
add_fileset_file "atax_bb_B11.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B11.sv"
add_fileset_file "atax_B11_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B11_branch.sv"
add_fileset_file "atax_B11_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B11_merge.sv"
add_fileset_file "atax_B11_merge_storage.sv" SYSTEM_VERILOG PATH "ip/atax_B11_merge_storage.sv"
add_fileset_file "atax_bb_B11_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B11_stall_region.sv"
add_fileset_file "atax_bb_B12.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B12.sv"
add_fileset_file "atax_B12_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B12_branch.sv"
add_fileset_file "atax_B12_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B12_merge.sv"
add_fileset_file "atax_B12_merge_storage.sv" SYSTEM_VERILOG PATH "ip/atax_B12_merge_storage.sv"
add_fileset_file "atax_bb_B12_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B12_stall_region.sv"
add_fileset_file "atax_i_sfc_s_c0_in_for_body73_s_c0_enter18714_atax1.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c0_in_for_body73_s_c0_enter18714_atax1.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_body73_s_c0_exit191_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_body73_s_c0_exit191_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0004_atax1_full_detector.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0004_atax1_full_detector.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000t191_atax1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000t191_atax1_data_fifo.sv"
add_fileset_file "atax_i_sfc_logic_s_c0_in_for_body73_s_c0_enter18714_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c0_in_for_body73_s_c0_enter18714_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_dummy_thread_b12_dummy_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_dummy_thread_b12_dummy_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_ffwd_dest_p1024f32_y_out4425_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_ffwd_dest_p1024f32_y_out4425_0.sv"
add_fileset_file "atax_i_llvm_fpga_forked_b12_forked_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_forked_b12_forked_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memdep_7_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memdep_7_0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_16_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_16_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notexitcond_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notexitcond_0.sv"
add_fileset_file "atax_bb_B13.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B13.sv"
add_fileset_file "atax_B13_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B13_branch.sv"
add_fileset_file "atax_B13_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B13_merge.sv"
add_fileset_file "atax_B13_merge_storage.sv" SYSTEM_VERILOG PATH "ip/atax_B13_merge_storage.sv"
add_fileset_file "atax_bb_B13_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B13_stall_region.sv"
add_fileset_file "atax_i_iowr_bl_return_unnamed_atax17_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_iowr_bl_return_unnamed_atax17_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_push_token_i1_throttle_push_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_token_i1_throttle_push_0.sv"
add_fileset_file "atax_bb_B1_start.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B1_start.sv"
add_fileset_file "atax_B1_start_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B1_start_branch.sv"
add_fileset_file "atax_B1_start_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B1_start_merge.sv"
add_fileset_file "atax_B1_start_merge_storage.sv" SYSTEM_VERILOG PATH "ip/atax_B1_start_merge_storage.sv"
add_fileset_file "atax_bb_B1_start_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B1_start_stall_region.sv"
add_fileset_file "atax_i_llvm_fpga_pop_throttle_i1_throttle_pop_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_throttle_i1_throttle_pop_0.sv"
add_fileset_file "atax_i_iord_bl_call_unnamed_atax1_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_iord_bl_call_unnamed_atax1_atax0.sv"
add_fileset_file "atax_i_sfc_s_c0_in_wt_entry_s_c0_enter11_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c0_in_wt_entry_s_c0_enter11_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_wt_entry_s_c0_exit_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_wt_entry_s_c0_exit_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_wt_en0000_atax1_full_detector.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_wt_en0000_atax1_full_detector.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_wt_en0000exit_atax1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_wt_en0000exit_atax1_data_fifo.sv"
add_fileset_file "atax_i_sfc_logic_s_c0_in_wt_entry_s_c0_enter11_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c0_in_wt_entry_s_c0_enter11_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_dummy_thread_b1_start_dummy_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_dummy_thread_b1_start_dummy_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_forked_b1_start_forked_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_forked_b1_start_forked_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going52_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going52_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notexitcond53_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notexitcond53_0.sv"
add_fileset_file "atax_i_sfc_s_c1_in_wt_entry_s_c1_enter_atax4.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c1_in_wt_entry_s_c1_enter_atax4.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c1_out_wt_entry_s_c1_exit_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c1_out_wt_entry_s_c1_exit_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c1_out_wt_en0000_atax1_full_detector.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c1_out_wt_en0000_atax1_full_detector.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c1_out_wt_en0000exit_atax1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c1_out_wt_en0000exit_atax1_data_fifo.sv"
add_fileset_file "atax_i_sfc_logic_s_c1_in_wt_entry_s_c1_enter_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c1_in_wt_entry_s_c1_enter_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_ffwd_source_p1024a64f32_unnamed_2_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_ffwd_source_p1024a64f32_unnamed_2_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_ffwd_source_p1024f32_unnamed_3_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_ffwd_source_p1024f32_unnamed_3_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_ffwd_source_p1024f32_unnamed_4_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_ffwd_source_p1024f32_unnamed_4_atax0.sv"
add_fileset_file "atax_bb_B2.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B2.sv"
add_fileset_file "atax_B2_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B2_branch.sv"
add_fileset_file "atax_B2_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B2_merge.sv"
add_fileset_file "atax_B2_merge_storage.sv" SYSTEM_VERILOG PATH "ip/atax_B2_merge_storage.sv"
add_fileset_file "atax_bb_B2_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B2_stall_region.sv"
add_fileset_file "atax_bb_B3.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B3.sv"
add_fileset_file "atax_B3_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B3_branch.sv"
add_fileset_file "atax_B3_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B3_merge.sv"
add_fileset_file "atax_B3_merge_storage.sv" SYSTEM_VERILOG PATH "ip/atax_B3_merge_storage.sv"
add_fileset_file "atax_bb_B3_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B3_stall_region.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_7_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_7_atax0.sv"
add_fileset_file "atax_i_sfc_s_c0_in_for_body_s_c0_enter9612_atax1.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c0_in_for_body_s_c0_enter9612_atax1.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_body_s_c0_exit98_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_body_s_c0_exit98_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000_atax1_full_detector.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000_atax1_full_detector.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000it98_atax1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000it98_atax1_data_fifo.sv"
add_fileset_file "atax_i_sfc_logic_s_c0_in_for_body_s_c0_enter9612_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c0_in_for_body_s_c0_enter9612_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_dummy_thread_b3_dummy_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_dummy_thread_b3_dummy_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_ffwd_dest_p1024f32_x4324_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_ffwd_dest_p1024f32_x4324_0.sv"
add_fileset_file "atax_i_llvm_fpga_forked_b3_forked_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_forked_b3_forked_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memdep_2_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memdep_2_0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memdep_3_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memdep_3_0.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going48_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going48_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notexitcond49_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notexitcond49_0.sv"
add_fileset_file "atax_i_sfc_s_c1_in_for_body_s_c1_enter101_atax5.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c1_in_for_body_s_c1_enter101_atax5.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c1_out_for_body_s_c1_exit103_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c1_out_for_body_s_c1_exit103_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c1_out_for_b0000_atax1_full_detector.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c1_out_for_b0000_atax1_full_detector.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c1_out_for_b0000t103_atax1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c1_out_for_b0000t103_atax1_data_fifo.sv"
add_fileset_file "atax_i_sfc_logic_s_c1_in_for_body_s_c1_enter101_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c1_in_for_body_s_c1_enter101_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memdep_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memdep_0.sv"
add_fileset_file "atax_bb_B4.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B4.sv"
add_fileset_file "atax_B4_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B4_branch.sv"
add_fileset_file "atax_B4_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B4_merge.sv"
add_fileset_file "atax_B4_merge_storage.sv" SYSTEM_VERILOG PATH "ip/atax_B4_merge_storage.sv"
add_fileset_file "atax_bb_B4_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B4_stall_region.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_9_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_9_atax0.sv"
add_fileset_file "atax_i_sfc_s_c0_in_for_body13_s_c0_enter10515_atax3.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c0_in_for_body13_s_c0_enter10515_atax3.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_body13_s_c0_exit111_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_body13_s_c0_exit111_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0001_atax1_full_detector.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0001_atax1_full_detector.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000t111_atax1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000t111_atax1_data_fifo.sv"
add_fileset_file "atax_i_sfc_logic_s_c0_in_for_body13_s_c0_enter10515_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c0_in_for_body13_s_c0_enter10515_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_dummy_thread_b4_dummy_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_dummy_thread_b4_dummy_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_ffwd_dest_p1024a64f32_a4223_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_ffwd_dest_p1024a64f32_a4223_0.sv"
add_fileset_file "atax_i_llvm_fpga_forked_b4_forked_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_forked_b4_forked_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going43_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going43_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notexitcond44_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notexitcond44_0.sv"
add_fileset_file "atax_i_sfc_s_c1_in_for_body13_s_c1_enter118_atax7.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c1_in_for_body13_s_c1_enter118_atax7.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c1_out_for_body13_s_c1_exit121_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c1_out_for_body13_s_c1_exit121_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c1_out_for_b0001_atax1_full_detector.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c1_out_for_b0001_atax1_full_detector.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c1_out_for_b0000t121_atax1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c1_out_for_b0000t121_atax1_data_fifo.sv"
add_fileset_file "atax_i_sfc_logic_s_c1_in_for_body13_s_c1_enter118_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c1_in_for_body13_s_c1_enter118_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memdep_4_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memdep_4_0.sv"
add_fileset_file "atax_bb_B5.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B5.sv"
add_fileset_file "atax_B5_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B5_branch.sv"
add_fileset_file "atax_B5_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B5_merge.sv"
add_fileset_file "atax_B5_merge_storage.sv" SYSTEM_VERILOG PATH "ip/atax_B5_merge_storage.sv"
add_fileset_file "atax_bb_B5_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B5_stall_region.sv"
add_fileset_file "atax_bb_B6.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B6.sv"
add_fileset_file "atax_B6_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B6_branch.sv"
add_fileset_file "atax_B6_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B6_merge.sv"
add_fileset_file "atax_B6_merge_storage.sv" SYSTEM_VERILOG PATH "ip/atax_B6_merge_storage.sv"
add_fileset_file "atax_bb_B6_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B6_stall_region.sv"
add_fileset_file "atax_i_sfc_s_c0_in_for_cond28_preheader_s_c0_enter12313_atax1.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c0_in_for_cond28_preheader_s_c0_enter12313_atax1.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_c0000r_s_c0_exit130_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_c0000r_s_c0_exit130_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_c0000_atax1_full_detector.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_c0000_atax1_full_detector.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_c0000t130_atax1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_c0000t130_atax1_data_fifo.sv"
add_fileset_file "atax_i_sfc_logic_s_c0_in_for_cond28_preh0000_c0_enter12313_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c0_in_for_cond28_preh0000_c0_enter12313_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_dummy_thread_b6_dummy_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_dummy_thread_b6_dummy_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_forked_b6_forked_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_forked_b6_forked_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_arrayidx32_promoted1_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_arrayidx32_promoted1_0.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going38_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going38_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notexitcond39_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notexitcond39_0.sv"
add_fileset_file "atax_bb_B7.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B7.sv"
add_fileset_file "atax_B7_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B7_branch.sv"
add_fileset_file "atax_B7_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B7_merge.sv"
add_fileset_file "atax_B7_merge_storage.sv" SYSTEM_VERILOG PATH "ip/atax_B7_merge_storage.sv"
add_fileset_file "atax_bb_B7_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B7_stall_region.sv"
add_fileset_file "atax_i_sfc_s_c0_in_for_body30_s_c0_enter13916_atax7.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c0_in_for_body30_s_c0_enter13916_atax7.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_body30_s_c0_exit149_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_body30_s_c0_exit149_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0002_atax1_full_detector.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0002_atax1_full_detector.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000t149_atax1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000t149_atax1_data_fifo.sv"
add_fileset_file "atax_i_sfc_logic_s_c0_in_for_body30_s_c0_enter13916_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c0_in_for_body30_s_c0_enter13916_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_dummy_thread_b7_dummy_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_dummy_thread_b7_dummy_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_forked_b7_forked_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_forked_b7_forked_atax0.sv"
add_fileset_file "atax_flt_i_sfc_logic_s_c0_in_for_body30_0000xk5id06uq0cp0jv34qcz.sv" SYSTEM_VERILOG PATH "ip/atax_flt_i_sfc_logic_s_c0_in_for_body30_0000xk5id06uq0cp0jv34qcz.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_11_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_11_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_12_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_12_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going33_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going33_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notexitcond34_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notexitcond34_0.sv"
add_fileset_file "atax_bb_B8.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B8.sv"
add_fileset_file "atax_B8_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B8_branch.sv"
add_fileset_file "atax_B8_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B8_merge.sv"
add_fileset_file "atax_B8_merge_storage.sv" SYSTEM_VERILOG PATH "ip/atax_B8_merge_storage.sv"
add_fileset_file "atax_bb_B8_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B8_stall_region.sv"
add_fileset_file "atax_i_llvm_fpga_pop_i1_memdep_phi_pop20_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pop_i1_memdep_phi_pop20_0.sv"
add_fileset_file "atax_i_sfc_s_c0_in_for_inc44_s_c0_enter158_atax3.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c0_in_for_inc44_s_c0_enter158_atax3.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_inc44_s_c0_exit161_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_inc44_s_c0_exit161_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_i0000_atax1_full_detector.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_i0000_atax1_full_detector.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_i0000t161_atax1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_i0000t161_atax1_data_fifo.sv"
add_fileset_file "atax_i_sfc_logic_s_c0_in_for_inc44_s_c0_enter158_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c0_in_for_inc44_s_c0_enter158_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memdep_5_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memdep_5_0.sv"
add_fileset_file "atax_bb_B9.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B9.sv"
add_fileset_file "atax_B9_branch.sv" SYSTEM_VERILOG PATH "ip/atax_B9_branch.sv"
add_fileset_file "atax_B9_merge.sv" SYSTEM_VERILOG PATH "ip/atax_B9_merge.sv"
add_fileset_file "atax_B9_merge_storage.sv" SYSTEM_VERILOG PATH "ip/atax_B9_merge_storage.sv"
add_fileset_file "atax_bb_B9_stall_region.sv" SYSTEM_VERILOG PATH "ip/atax_bb_B9_stall_region.sv"
add_fileset_file "atax_i_sfc_s_c0_in_for_body52_s_c0_enter16817_atax6.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_s_c0_in_for_body52_s_c0_enter16817_atax6.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_body52_s_c0_exit180_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_body52_s_c0_exit180_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0003_atax1_full_detector.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0003_atax1_full_detector.sv"
add_fileset_file "atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000t180_atax1_data_fifo.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_sfc_exit_s_c0_out_for_b0000t180_atax1_data_fifo.sv"
add_fileset_file "atax_i_sfc_logic_s_c0_in_for_body52_s_c0_enter16817_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_sfc_logic_s_c0_in_for_body52_s_c0_enter16817_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_dummy_thread_b9_dummy_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_dummy_thread_b9_dummy_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_forked_b9_forked_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_forked_b9_forked_atax0.sv"
add_fileset_file "atax_flt_i_sfc_logic_s_c0_in_for_body52_0000xk5id06uq0cp0jv34qcz.sv" SYSTEM_VERILOG PATH "ip/atax_flt_i_sfc_logic_s_c0_in_for_body52_0000xk5id06uq0cp0jv34qcz.sv"
add_fileset_file "atax_i_llvm_fpga_mem_memdep_6_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_memdep_6_0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_14_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_14_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_mem_unnamed_15_atax0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_mem_unnamed_15_atax0.sv"
add_fileset_file "atax_i_llvm_fpga_pipeline_keep_going28_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_pipeline_keep_going28_0.sv"
add_fileset_file "atax_i_llvm_fpga_push_i1_notexitcond29_0.sv" SYSTEM_VERILOG PATH "ip/atax_i_llvm_fpga_push_i1_notexitcond29_0.sv"
add_fileset_file "atax_start_pulse.sv" SYSTEM_VERILOG PATH "ip/atax_start_pulse.sv"
add_fileset_file "atax_wait_pulse_extender_inst.sv" SYSTEM_VERILOG PATH "ip/atax_wait_pulse_extender_inst.sv"
add_fileset_file "acl_avm_to_ic.v" SYSTEM_VERILOG PATH "ip/acl_avm_to_ic.v"
add_fileset_file "acl_ic_master_endpoint.v" SYSTEM_VERILOG PATH "ip/acl_ic_master_endpoint.v"
add_fileset_file "acl_arb_intf.v" SYSTEM_VERILOG PATH "ip/acl_arb_intf.v"
add_fileset_file "acl_ic_intf.v" SYSTEM_VERILOG PATH "ip/acl_ic_intf.v"
add_fileset_file "acl_ic_slave_endpoint.v" SYSTEM_VERILOG PATH "ip/acl_ic_slave_endpoint.v"
add_fileset_file "acl_ic_slave_rrp.v" SYSTEM_VERILOG PATH "ip/acl_ic_slave_rrp.v"
add_fileset_file "acl_ic_slave_wrp.v" SYSTEM_VERILOG PATH "ip/acl_ic_slave_wrp.v"
add_fileset_file "acl_arb2.v" SYSTEM_VERILOG PATH "ip/acl_arb2.v"
add_fileset_file "acl_ic_to_avm.v" SYSTEM_VERILOG PATH "ip/acl_ic_to_avm.v"
add_fileset_file "acl_mem1x.v" SYSTEM_VERILOG PATH "ip/acl_mem1x.v"
add_fileset_file "hld_ram.sv" SYSTEM_VERILOG PATH "ip/hld_ram.sv"
add_fileset_file "hld_ram_ecc.sv" SYSTEM_VERILOG PATH "ip/hld_ram_ecc.sv"
add_fileset_file "hld_ram_tall_depth_stitch.sv" SYSTEM_VERILOG PATH "ip/hld_ram_tall_depth_stitch.sv"
add_fileset_file "hld_ram_remaining_width.sv" SYSTEM_VERILOG PATH "ip/hld_ram_remaining_width.sv"
add_fileset_file "hld_ram_bits_per_enable.sv" SYSTEM_VERILOG PATH "ip/hld_ram_bits_per_enable.sv"
add_fileset_file "hld_ram_generic_two_way_depth_stitch.sv" SYSTEM_VERILOG PATH "ip/hld_ram_generic_two_way_depth_stitch.sv"
add_fileset_file "hld_ram_generic_three_way_depth_stitch.sv" SYSTEM_VERILOG PATH "ip/hld_ram_generic_three_way_depth_stitch.sv"
add_fileset_file "hld_ram_short_depth_stitch.sv" SYSTEM_VERILOG PATH "ip/hld_ram_short_depth_stitch.sv"
add_fileset_file "hld_ram_bottom_width_stitch.sv" SYSTEM_VERILOG PATH "ip/hld_ram_bottom_width_stitch.sv"
add_fileset_file "hld_ram_bottom_depth_stitch.sv" SYSTEM_VERILOG PATH "ip/hld_ram_bottom_depth_stitch.sv"
add_fileset_file "hld_ram_lower.sv" SYSTEM_VERILOG PATH "ip/hld_ram_lower.sv"
add_fileset_file "hld_ram_lower_mlab_simple_dual_port.sv" SYSTEM_VERILOG PATH "ip/hld_ram_lower_mlab_simple_dual_port.sv"
add_fileset_file "hld_ram_lower_m20k_simple_dual_port.sv" SYSTEM_VERILOG PATH "ip/hld_ram_lower_m20k_simple_dual_port.sv"
add_fileset_file "hld_ram_lower_m20k_true_dual_port.sv" SYSTEM_VERILOG PATH "ip/hld_ram_lower_m20k_true_dual_port.sv"
add_fileset_file "acl_ic_local_mem_router.v" SYSTEM_VERILOG PATH "ip/acl_ic_local_mem_router.v"
add_fileset_file "atax_internal.v" SYSTEM_VERILOG PATH "atax_internal.v"

#### Primary clock for the component
add_interface clock clock end
set_interface_property clock ENABLED true
set_interface_assignment clock hls.cosim.name {$clock}
add_interface_port clock clock clk input 1

#### Primary reset for the component
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_assignment reset hls.cosim.name {$reset}
add_interface_port reset resetn reset_n input 1

#### The component invocation protocol interface (call)
add_interface call conduit sink
set_interface_property call associatedClock clock
set_interface_property call associatedReset reset
set_interface_assignment call hls.cosim.name {$call}
add_interface_port call start valid input 1
add_interface_port call busy stall output 1

#### The component return protocol interface (return)
add_interface return conduit source
set_interface_property return associatedClock clock
set_interface_property return associatedReset reset
set_interface_assignment return hls.cosim.name {$return}
add_interface_port return done valid output 1
add_interface_port return stall stall input 1

#### Parameter A interface
add_interface A conduit sink
set_interface_property A associatedClock clock
set_interface_property A associatedReset reset
set_interface_assignment A hls.cosim.name {A}
add_interface_port A A data input 64

#### Parameter x interface
add_interface x conduit sink
set_interface_property x associatedClock clock
set_interface_property x associatedReset reset
set_interface_assignment x hls.cosim.name {x}
add_interface_port x x data input 64

#### Parameter y_out interface
add_interface y_out conduit sink
set_interface_property y_out associatedClock clock
set_interface_property y_out associatedReset reset
set_interface_assignment y_out hls.cosim.name {y_out}
add_interface_port y_out y_out data input 64

#### Master interface avmm_0_rw with base address 0
add_interface avmm_0_rw avalon start
set_interface_property avmm_0_rw ENABLED true
set_interface_property avmm_0_rw associatedClock clock
set_interface_property avmm_0_rw burstOnBurstBoundariesOnly false
set_interface_property avmm_0_rw doStreamReads false
set_interface_property avmm_0_rw doStreamWrites false
set_interface_property avmm_0_rw linewrapBursts false
set_interface_property avmm_0_rw readWaitTime 0
set_interface_property avmm_0_rw readLatency 1
add_interface_port avmm_0_rw avmm_0_rw_address address output 64
add_interface_port avmm_0_rw avmm_0_rw_byteenable byteenable output 8
add_interface_port avmm_0_rw avmm_0_rw_read read output 1
add_interface_port avmm_0_rw avmm_0_rw_readdata readdata input 64
add_interface_port avmm_0_rw avmm_0_rw_write write output 1
add_interface_port avmm_0_rw avmm_0_rw_writedata writedata output 64

#### Quartus settings (QIP strings)
set_qip_strings { "set_instance_assignment -entity \"%entityName%\" -library \"%libraryName%\" -name AUTO_SHIFT_REGISTER_RECOGNITION OFF -to *_NO_SHIFT_REG*"  }
